### ISSUE TITLE
Move Context deriviation function to a different location

### ISSUE THREAD

**Issue by jimsch** [core-wg/oscoap#1]
Section 3 - I like the fact that the security context is being defined, however I question the wisdom of including the sections on how to derive a context from a shared secret at this point.  I think it would make more sense to put this into the EDHOC document, and if you do not do that then to at least move this into an appendix.  I do not believe that this is/should be the only method to populate a context.  I would hope that a method of doing so from a CWT will be defined as that may have the advantage of getting more controlled random numbers.  From a security analysis point of view, there is no difference between get the shared secret used here or the actual keys from a third party.  There is a difference if EDHOC is used.

**Comment by fpalombini** [comment]
For different reasons, we would rather not change the document to allow it in the draft:
- simplicity
- memory saving (by being able to delete the context if you keep the master secret)
- the master secret is smaller than the security context to transport

We don't see a compelling use case.
