### ISSUE TITLE
Initizialization of Sequence numbers

### ISSUE THREAD

**Issue by Gunzter** [core-wg/oscoap#101]
In a previous version the method for composing a OSCOAP message was:
-Sequence Number++
-Compose AAD + COSE etc.

Now it is the other way around i.e:
-Compose AAD + COSE etc.
-Sequence Number++

When sequence numbers are initialized to 0 this causes the Server to reject the first reqest incoming with Seq=0 as a replay. If you initialize the Recipient Seq (or Last Seen) to -1 for example this is no problem.
However, on my constrained implementation I use unsigned integers for sequence numbers so such a solution is unattractive.
Were there any reason to change to the new method (composing a message THEN incrementing) that I have missed?

**Comment by gselander** [comment]
Replay protection and replay window length is application specific and depends on the lower layers, but the sequence number is initialized to zero to align with DTLS, which is the default replay mechanism:
https://tools.ietf.org/html/rfc6347#section-4.1.2.6

In the referenced section it is indicated a method using a bit mask, would that work for you?

**Comment by Gunzter** [comment]
The method of using a bit mask works. 
The thing I had an issue with is that sequence numbers begin at 0. When initializing the servers recipient sequence numbers to 0 the server will reject the first message as a replay. But the stated intention of aligning the replay protection with DTLS is a valid one. I will have to come up with a solution to this rather minor problem.
I am closing the issue.
