### ISSUE TITLE
Section 6.3.1. contains normative references a draft that is not even adopted

### ISSUE THREAD

**Issue by LudwigSeitz** [core-wg/oscoap#102]
In section 6.3.1. draft-mattsson-core-coap-actuators is referenced in a normative way (although with MAY). I don't think that is wise, we should not create dependencies on drafts that will potentially take longer to be finalized (or that will never be finalized).

**Comment by chrysn** [comment]
Without coap-actuators, a flash-based server will have a hard time communicating with a Repeat-unaware client, so IMO the normative reference is a good thing (and possibly needs to add that a client SHOULD support the Repeat option).

**Comment by fpalombini** [comment]
Following IETF98, it was concluded that OSCOAP shall normatively reference a solution that solve this (say a repeat option), as well as the blockwise issue (say request-tag).
