### ISSUE TITLE
Appendix A shouldn't be an appendix and needs clarification

### ISSUE THREAD

**Issue by LudwigSeitz** [core-wg/oscoap#104]
Appendix A specifies normative procedures and shouldn't be an appendix. Also the text is not clear by far, especially this sentence: "Furthermore, the type and length for the ciphertext is redundant and 10 bits in the first two bytes are static." Please clarify, the first two bytes of what, the ciphertext or the CBOR array?

Also this is not clear: "The exception is Responses without Observe that SHALL be encoded as:"  Exception to what? To the encoding specified above I suspect and not to the redundancy of type-length, but this could be significantly improved.

**Comment by jimsch** [comment]
YES +++1

**Comment by T0bbe** [comment]
I strongly support Ludwig. Also, after a long email conversation I had with Christian Amsüss, he clarified for me that the example A.1.1., the part that says "before compression" is the result without compression and not the COSE object before compression. Since, following the byte fiddling as explained in the text, 83 47 doesn't encodes to 19, but 83 41 does. This example needs to be clarified.

**Comment by gselander** [comment]
Francesca proposed in a different thread that it would be good with the intermediate step:

[h'05', h'25', h'aea0155667924dff8a24e4cb35b9']
83  41  05 41 25 4e ae a0 etc. 

@T0bbe: Would that make things clearer?

**Comment by T0bbe** [comment]
@gselander It would, I like this suggestion. But also remove/re-write "before compression" to something e.g. "the result when compression is not used". And/or add a description, since now it is quite confusing.

**Comment by gselander** [comment]
@core-bot: Hi Carsten 

In the context of this example A.1.1, considering that the previous step is:

[
h'a2044125064105'   / { 4:h'25', 6:h'05' } /,
{},
h'aea0155667924dff8a24e4cb35b9'
]

In this case, in think spelling out the compression makes sense without pretty print?

 [h'05', h'25', h’aea0155667924dff8a24e4cb35b9']

**Comment by gselander** [comment]
@T0bbe: OK, we'll try to clarify in text as well.

**Comment by cabo** [comment]
@gselander Sure; my comment was about when you show raw hex -- then you should generally be using prettyprinting.  Diagnostic notation doesn't always need (the other form of) prettyprinting, in particular when as short as in this example.
