### ISSUE TITLE
Need to get some justification on using the TID as an input to authenticated data

### ISSUE THREAD

**Issue by jimsch** [core-wg/oscoap#11]
Section 3.2 - I would like to see a justification of using the Tid as a value that needs to be authenticated as part of the message.  I don't see it in this anyplace.  It should be part of a security argument.

**Comment by fpalombini** [comment]
Doesn't the 4th paragraph of section 6.1 provide the justification?

"OSCOAP is a challenge-response protocol, where the response is verified to match a prior request, by including the unique transaction identifier (Tid as defined in Section 3) of the request in the Additional Authenticated Data of the response message."

**Comment by fpalombini** [comment]
from offline discussion, this requires some analysis about whether the Cid and Sender ID are necessary to be included (for security reasons) in the external aad and should be included in the security considerations.

**Comment by emanjon** [comment]
Fixed in brach v-02
