### ISSUE TITLE
sequence number processing is wrong

### ISSUE THREAD

**Issue by fpalombini** [core-wg/oscoap#116]
in section 7.1 and 7.3, the nonce is created, then the seq is incremented, and then the COSE object is created, which means that the seq sent is not the same as the one used to create the nonce.

**Comment by T0bbe** [comment]
Couldn't one simply move the increment of the sequence number to a later stage in the process? Maybe as a final step.

**Comment by jimsch** [comment]
My implementation basically does the increment of the serial number as the final step.  If it fails at one of the previous steps before I try and send the message it does not really matter if a duplicate is used.  The first is not going to be seen.  Some purists would disagree and say that we should skip once an encrypt is done.
