### ISSUE TITLE
Move text for multicast to the multi cast document

### ISSUE THREAD

**Issue by jimsch** [core-wg/oscoap#12]
-00

Section 3.2.3 - You are getting ahead of yourself.  The only way that the identifiers would not be unique would be if the sender and recipient collided.  I do not know that this would be a problem and therefore talking about it makes no sense.  I am assuming that this is supposed to have something to do with the multicast work that I have not looked at.  If so it does not belong here but there.

**Comment by emanjon** [comment]
Agree. I'll delete all text on group communication from the document.

**Comment by emanjon** [comment]
Multicast removed in branch v-02
