### ISSUE TITLE
Contradictions between section 5 - COSE and 8 - OSCOAP Compression

### ISSUE THREAD

**Issue by Gunzter** [core-wg/oscoap#121]
From Section 5:
>    The “Partial IV” parameter. The value is set to the Sequence Number. The Partial IV SHALL be of minimum length needed to encode the sequence number. This parameter SHALL be present in requests, **and MAY be present in responses**. In case of Observe (Section 4.3.2.1}) the **Partial IV SHALL be present in the response.**
>     The “kid” parameter. The value is set to the Sender ID (see Section 3). This parameter SHALL be present in requests and **SHALL NOT be present in responses.**

From Section 8
> In requests, Partial IV and kid MUST be present; counter signature and group Identifier MUST NOT be present. In responses without observe, **Partial IV, kid, counter signature and group Identifier MUST NOT be present.** In responses with observe, **kid MUST be present;** Partial IV, counter signature and group Identifier MUST NOT be present.

Contradictions marked in bold.

**Comment by fpalombini** [comment]
Thank you for pointing this out Martin. The main contradiction is that I mixed up kid and Partial IV in this sentence: 

> In responses with observe, kid MUST be present; Partial IV, counter signature and group Identifier MUST NOT be present.

It should have been: 

> In responses with observe, Partial IV MUST be present; kid, counter signature and group Identifier MUST NOT be present.

I'm ok with the changes in bd37819 (namely remove counter signature and group id here), but I'd rather lines 692 693 and 694 be kept there. I think it helps for practical reasons to have this information here, which can of course be found in section 5, but is summarized in a different way here. I find it clearer and simpler to see what bits to set in the flag byte. 

Also, did you think the bits indication was not enough? I think it is more confusing than simplifying to add the half-byte consideration.

**Comment by Gunzter** [comment]
Yea, I found the bit indications rather clear. To aid implementation I make schematics of the first byte and the meaning of each bit and the other fields. I think section 8 can possibly benefit from some kind of illustration.
