### ISSUE TITLE
Typo in section 8

### ISSUE THREAD

**Issue by Gunzter** [core-wg/oscoap#122]
`The following x bytes (x given by the previous byte) encode the value of the kid, if the kid is present (flag bit set to 1)`

I assume that `kid` is supposed to be counter signature, because this field is after the length field for the counter signature field.

**Comment by gselander** [comment]
I removed specification of compression of counter signature and group identifier from this specification, and will introduce the compression of these parameters in the multicast OSCOAP draft. Therefore this comment is not relevant anymore so I close the issue.
