### ISSUE TITLE
OSCOAP, blocking and TCP needs to be documented

### ISSUE THREAD

**Issue by jimsch** [core-wg/oscoap#124]
So in the process of trying to get a TCP implementation done, I came up with the following issue.  It defines BERT and a mechanism to say that blocking is not supported as well as changing the maximum message size.  These interact in a normal way with the Outer Blocking because it is defined in the TCP document.

How do these options interact with the inner blocking?  it is possible that the interaction is going to be different if there is a proxy URI on the message so it needs to be covered.  One cannot just assume that the same rules apply or inner and outer blocking.

**Comment by gselander** [comment]
Right, one cannot just assume that the same rules apply, but I couldn't find any difference compared to other block options.

Outer block options are handled as defined in the TCP draft. Inner block options are already class E so in particular SZX=7 and the entire payload will be encrypted and integrity protected. So OSCOAP will interact with the BERT implementation and hand over the message at the receiving side as left off from BERT at the sending side, if the message verifies.

Max-Message-Size Capability and Block-wise Transfer, like other block-related options can be used as inner and/or outer options.  Again the outer options guide the hop-by-hop behaviour and changes are verified when received at the destination endpoint. OSCOAP recommends new options to be class E, and this can be applied when they are used as inner options between the endpoints. To the intermediate nodes, the inner BERT messages are just like large CoAP messages and must be handled accordingly. What would be different with proxy URI?

**Comment by jimsch** [comment]
If you have the situation of Client->TCP->Proxy->UDP->Server, it might be better to say that you are going to do lots of inner messages across the entire eco-system rather than one big one from client to proxy and have the proxy do the break up as an outer blocking.  Similar if you reverse TCP and UDP - are you better doing one large inner block on the first link so it can be combined in the second link?

I dont know the answer to ether and I realize that the two are opposite arguments.

**Comment by gselander** [comment]
I take it this about recommendations for fragmentation for performance purposes, not about security issues. Is that correct?

As you note, it is not obvious what is optimal and this is a potential subject for test and analysis.

In general, if there is just one hop with limited capacity, then outer blockwise on that passage seems most efficient (in which case the OSCOAP endpoints doesn't do anything). If there are many hops with limited capacity, then if the endpoint sizes inner blocks to match that capacity seems best. And the two may become combined if the most limited hop is significantly slower than the rest. I don't know how that translate to mixed TCP/UDP, but in any case, the endpoints can only act upon the information they have and it should work in either case. Disregarding the optimization problem, do you see any issue with the functional part?

**Comment by jimsch** [comment]
Yes this is a performance issue and not a security issue.

I would suggest sending to the list to see if people have any ideas on what the trade offs would be.

**Comment by chrysn** [comment]
The Max-Message-Size is a CSM option; unless we specify that they are OK inside OSCOAP, I don't think we can use them. Also BERT has been [discussed to be possibly applicable](https://mailarchive.ietf.org/arch/msg/core/eSIvYZ-hH1oDGtNRQImJbzzaYrQ) to (or specified for) TCP only.

**Comment by jimsch** [comment]
Two responses to this.
1.  I am not suggesting that the Max-Message-Size be transmitted as part of OSCOAP.  I am asking how this would effect the block size when doing a block-wise transfer inside of an OSCOAP message. 
2.  My worry about BERT is not using BERT inside of OSCOAP but again how it should affect the use of block wise transfers inside of OSCOAP.  If BERT exists, then a single message may be more efficient than doing blocking inside of OSCOAP.  --- See Hannes's comment on the efficiency of not using BERT over TCP here https://mailarchive.ietf.org/arch/msg/core/x5vWm_NfRXFJeTe5elRITymMJ5Q

**Comment by gselander** [comment]
So what remains is to include a paragraph on trade-offs when using inner and outer block fragmentation in the case of BERT.
