### ISSUE TITLE
OSCOAP errors: protected or not?

### ISSUE THREAD

**Issue by fpalombini** [core-wg/oscoap#126]
Right now it is unclear from the text if OSCOAP errors (ie CoAP error messages generated if OSCOAP processing goes wrong in case of CON messages) are protected with OSCOAP or not.

If the server cannot find the right security context or if the server cannot decode COSE or decompress the message, (Section 7.2 bullet 2) the server has no way to know what security context to use to protect an error message back.

The other 2 types of errors (replay and decryption/verification fails) could in theory be protected with OSCOAP. The question is would it make sense to protect those?

My proposal is not to protect any error created from OSCOAP processing failures.

**Comment by chrysn** [comment]
Given that we don't encrypt the response codes, and at least some of the errors can be told apart, we don't leak much information to an attacker when sending plain errors, but make debugging a lot easier. (From the current error codes, the only information to gain is whether it's a replay protection or a decryption failure).

**Comment by gselander** [comment]
Closing this issue: Error messages are not protected.
