### ISSUE TITLE
When is sending a partial IV ok?

### ISSUE THREAD

**Issue by chrysn** [core-wg/oscoap#127]
Today's plugtest has shown different interpretations of whether the server should, in its first response, use the bitflipped request partial IV or mint an own one. I'd use the bitflipped one because by the time the client decodes it, it can't even know whether the server does even support observation on that resource. (It certainly got the information in the inner message, but might not make an observation of it because a proxy might not support that.)

I'd argue that under any circumstances it should be permissible to use an own partial IV, because

* as above, not all requested observations become observations,
* with multicast, we'll see server-provided partial IVs in more situations, and most importantly:
* a server that can't retain packages for as long as it would need to keep them for retransmission would be free to create a different response (wasting an own sequence number) to satisfy the retransmitted request without worrying about resource state that might have changed when trying to reconstruct the original response bytewise (which would be required if it wanted to re-use the flipped partial IV).

**Comment by chrysn** [comment]
One point for using server-issued sequence numbers (or for always allowing both): A proxy is, AFAIR, free to swallow the initial response and send a later response under the eventual-consistency rules (eg. if the network interface to the client is overloaded, and the origin server's first update arrives before the initial response was sent).

**Comment by T0bbe** [comment]
According to the Observe RFC 7641: "A server that is unable or unwilling to add a new entry to the list of observers of a resource MAY silently ignore the registration request and process the GET request as usual.  The resulting response MUST NOT include an Observe Option, the absence of which signals to the client that it will not be notified of changes to the resource and, e.g., needs to poll the resource for its state instead."

Will not the proxy simple remove the outer Observe option if it doesn't support it? Thus, the client will now that the resource is not observable.

**Comment by gselander** [comment]
Let's recap: Observe is a special class I option (and the only class I option defined so far). Observe is only an outer option and this outer option is present if and only if Observe is used, but the outer value is not integrity protected. Observe in the request is not integrity protected at all. Observe in the response is integrity protected in the sense that part of the response PIV (Sequence Number) is included in the external_aad.

1. I think allowing both bitflipped request PIV and response PIV in first Observe response is an unnecessary complication.

Except for the case when a proxy removes the Observe option - in which case this becomes an ordinary request-response without Observe - please remind me if there is a compelling reason why we should allow the bitflipped request PIV in the first Observe response, instead of always use response PIV in all Observe responses? (There are a few bytes to gain in the first Observe response, but I didn't find that compelling)

2. If you agree on 1.  I think we should define the state of a client receiving a response to an Observe request which contains a response PIV (i.e. Sequence Number) but not the Observe option as an error.

**Comment by chrysn** [comment]
The situation that I think could justify allowing bitflipped responses is when the client requests an observation on a server that doesn't support observation at all. That server would need to trigger a mechanism it otherwise never needs (especially if it's so constrained it doesn't even have client functionality) just for those requests.

(My impression of the optionality of block and observe in new CoAP extensions is that they should not be published without consideration for those two basic extensions, but that they shouldn't mandate it for applications that can otherwise do fine without them).

**Comment by gselander** [comment]
I may be wrong but as I read the text below from RFC7641 a server that doesn't support Observe at all can respond just as a normal request. Which would then be the bitflipped PIV. Is there actually an issue here?

   "A server that is unable or unwilling to add a new entry to the list
   of observers of a resource MAY silently ignore the registration
   request and process the GET request as usual.  The resulting response
   MUST NOT include an Observe Option, the absence of which signals to
   the client that it will not be notified of changes to the resource
   and, e.g., needs to poll the resource for its state instead."

**Comment by chrysn** [comment]
Cc'ing @fpalombini and @jimsch as we talked about this today and yesterday, respectively.

I concede that my considerations for server simplification (as pointed out in @gselander's and @T0bbe's comments). However, the points about a proxy swallowing the initial (bitflipped) response and only forwarding the (server-minted) first update still stand, as does the point about clients that do not want to remember their state for retransmission or the transmitted package.

Most importantly, though, I think this makes message decoding more straight forward (because there are fewer error possibilities, just the two code paths that need to be there anyway) without changing anything about the actual message format or adding complexity.

**Comment by gselander** [comment]
For clarification: In case of Observe, do you propose both alternatives should be supported (bit flipped response and server-counted)  or that the server always does bit-flipped first response?

**Comment by jimsch** [comment]
The proposal is that both would be supported from the receiver.  I don't think we are making a requirement on the server send, but my preference would be bit-flipped.

**Comment by gselander** [comment]
To simplify, we decided in the discussion at the F2F meeting to mandate server behaviour. Jim changed his mind that the preference would be the use of the server-counted Partial IV, which is how it is currently written:

Protecting the response: 
"If Observe is used, compose the AEAD nonce by XORing the Context IV (Sender IV) with the Partial IV of the response (Sequence Number in network byte order)."

Verifying the response:
"If the Observe option is present in the response, compose the AEAD nonce by XORing the Context IV (Recipient IV) with the padded Partial IV parameter from the response."

An observe request transformed into a normal request will be protected and verified as a normal response.
