### ISSUE TITLE
Trusted connections to proxies

### ISSUE THREAD

**Issue by chrysn** [core-wg/oscoap#132]
There has been earlier discussion that we don't need to support nested OSCOAP, but what about OSCOAP securing only the way to a forward proxy?

I think that the most realistic use case is a forward cross protocol proxy; the constrained client would have a secured connection only to the proxy, and the proxy would use HTTPS or so from there. Admittedly that's not the primary use case for OSCOAP (one could just use DTLS there), but I'd expect that if OSCOAP gains wide use, it may also be used there.

Would it, for such uses (ie. iff the security context is to a forward proxy and not the origin server), be permissible to treat Proxy-Uri or Proxy-Scheme and Uri-Host as Class E options?

And as with an earlier issue: Should we think about that, or is that just out of scope, and if so, should we state that?

**Comment by gselander** [comment]
There may be many potential nestings of COSE objects. What are the most interesting use cases?

One use case as you mention is to protect some of the unprotected options for the proxy.

Another use case for double protection is described in issue #34 with solution proposed in Appendix D of the multicast OSCOAP draft:
https://ericssonresearch.github.io/Multicast-OSCOAP/#rfc.appendix.D
(note the message should ONLY be signed, not encrypted)

In issue #34 it is assumed that (D)TLS is used hop-by-hop and OSCOAP end-to-end, but we could   define OSCOAP in OSCOAP to replace transport layer security in that use case.

If we want this I think it is straightforward to define: The end-to-end protected (signed) CoAP message is treated as a hop-by-hop unprotected CoAP message, and run through OSCOAP once more before being sent. AFAICT, the only missing part is to describe how the Object-Security option should be treated by OSCOAP and if I'm not mistaken it should be a Class E option with outer and inner values:

In the case the method supports payload, then the second OSCOAP transformation becomes:

(Header, U-Options, O-S, CCO1) --> (Header, U-Options, O-S, CCO2)

where 
- CCO means Compressed COSE Object
- the payload CCO1 is signed
- the payload CCO2 is encrypting the empty O-S option and CCO2 

In the case of no payload, the second OSCOAP transformation becomes:

(Header, U-Options, O-S: CCO1) --> (Header, U-Options, O-S: CCO2)

where the O-S option value CCO2 is encrypting the O-S option with value CCO1.


In this use case, the end-to-end unprotected options (Proxy-Uri etc.) remain unprotected. Should we address any of these use cases (or both), or leave that for a later complementing specification?

**Comment by gselander** [comment]
For simplicity we propose to leave this for a later complementing specification. Reopen this issue if you think we should solve it now.
