### ISSUE TITLE
Proxy-Uri deconstruction for exotic schemes

### ISSUE THREAD

**Issue by chrysn** [core-wg/oscoap#133]
The Proxy-Uri section prescribes that Proxy-Uri be split up, but that's not necessarily possible with all URI schemes ("this case is only applicable if the components of the desired URI other than the scheme component actually can be expressed using Uri-* options").

Such a URI in an OSCOAP package happen if OSCOAP can be extended to a different protocol than CoAP. With HTTP it's probably safe (see #131; H-C is unaffected because the URI is a coap:// URI, and OSCOAP with a C-H proxy is unrealistic), but who knows where the road is going, and the text reads as if that  always works.

I'd suggest to add a text like this:

> [... MUST be replaced with Proxy-Scheme ...]
> This replacement works by design for all CoAP URIs, and OSCOAP aware HTTP servers should not use the userinfo component of the HTTP URI. When proxying to protocols with different URI structures is specified, it is expected that the authors will create Uri-* options that allow decomposing the Proxy-Uri, and specify in which classes they are.

**Comment by gselander** [comment]
I think it is fine to add some text about what assumptions are made. Let's first progress the HTTP-CoAP proxy issue #131 , so we can match the scope of that.

**Comment by gselander** [comment]
Having decided on #131 your proposal makes sense, let's include it.
