### ISSUE TITLE
Does a client need to verify a server's sequence number against the replay window?

### ISSUE THREAD

**Issue by chrysn** [core-wg/oscoap#139]
Thinking through what #127 means to small clients that neither start observations nor ever act as a server (ie. are classically not expected to deal with server-minted sequence numbers ever) but suddenly can get server-minted sequence numbers because the server may do so, the following question arose (though it's a question that's independent of #127 as it needs to be answered for regular observation as well):

Is it, when verifying a response, necessary to look up the server-provided sequence number in the replay window?

I think it is not, because it is shown in the AAD that this is a response to a request the client sent with its unique sequence number. The server is responsible for using the IV only once, and that one generated response only matches the request. The client can be free to check the sever-minted sequence numbers of responses against its replay window, or just plain ignore them (and thus, if it's not a server, run completely without a replay window) -- it doesn't add to security.

(By the way, if the client doesn't have a persisted replay window, it can't even sync with Repeat because it doesn't work in that direction -- but if I'm right with the above, that's not a problem.)

If it is not necessary to look that up, we should state that clearly in OSCOAP.

**Comment by chrysn** [comment]
Jim thinks that people will get this wrong, probably.

**Comment by chrysn** [comment]
I got https://github.com/core-wg/oscoap/issues/139#issuecomment-316060884 wrong -- that pertained to #120.

As I understand yesterday's lunch meeting, what I described (the client need not check the server's response sequence number) is fine.

**Comment by gselander** [comment]
The observe replay window is now removed.
