### ISSUE TITLE
Make Observe a class U option

### ISSUE THREAD

**Issue by chrysn** [core-wg/oscoap#140]
Cc @fpalombini and @jimsch as this is (my view of, with some enhancement) what we talked about yesterday during the interop.

We can make Observe a regular Class "U*" (ie. outer-only, with some special handling) option. The only special handling it needs is that the client verify that the order of outer Observe values equals the order of sequence numbers.

The trivial way to do that (which most libraries will want to do) is to discard any messages whose Observe value is lower than the last one seen (which is the normal mode of observation anyway), and then check whether the sequence numbers are ascending.

A library that chooses to expose older observe notifications to the application as well (which is not really supported in observe, but if the data makes it through the proxies, someone might want to use it) doesn't even (that's a change to our talk yesterday) need to synthesize option numbers, it can just use the last hop's numbers to present to the application (which will then recognize them as old data but make some use of them), but needs to check that the orders match. (If they don't, there is a malicious proxy inbetween.)

I'm indifferent as of whether we put the text about "orders must match" in the document (and explain that it's much simpler unless you do the fancy), or whether we put "must check that sequence numbers are ascending and discard anything else" in the document, and demote the sharper but more complex condition to an appendix (or even not publish it) for expert use only.

This makes #137 obsolete.

**Comment by gselander** [comment]
Closed in dac16e9
