### ISSUE TITLE
URI-Path options are wrong (I think)

### ISSUE THREAD

**Issue by jimsch** [core-wg/oscoap#143]
After the conversations with Dave Thaler, I started looking at the proxy code that I have in my project.  Based on what I am seeing, I am beginning to think that the rules for dealing with Uri-Path are incorrect.  Specifically consider doing the following:

Get coap://proxy.example.com/coap2coap
    Proxy-Uri = "coap://server.example.com/resource"

In this case there are going to be two distinct sets of Uri-Path options, one inner set and one outer set that are distinct as path to the proxy is not protected and the path to the server is protected.  Thus looking like

Get coap://proxy.example.com/coap2coap
    Proxy-Uri= "coap://server.example.com"
    ENCRYPTED{ Uri-Path="/resource" }

**Comment by fpalombini** [comment]
Maybe I don't understand exactly your example, but you can either have a Proxy-Uri option or you can have the set of Uri-* + Proxy-scheme in a request, not both .

```
   The Proxy-Uri Option MUST take precedence over any of the Uri-Host,
   Uri-Port, Uri-Path or Uri-Query options (each of which MUST NOT be
   included in a request containing the Proxy-Uri Option).
```
from [RFC7252 section 5.10.2](https://tools.ietf.org/html/rfc7252#section-5.10.2)
and [sec requirements section 2.2.1.3](https://tools.ietf.org/html/draft-hartke-core-e2e-security-reqs-02#section-2.2.1.3)

Is there anything I haven't considered?

**Comment by jimsch** [comment]
It is stupid - I have sent a message to core about it.

**Comment by fpalombini** [comment]
Thanks Jim. For anyone wishing to follow the discussion in the ML: 

https://mailarchive.ietf.org/arch/msg/core/fVDT77PPRPC8vvIbDoekagIsKRg

**Comment by fpalombini** [comment]
@jimsch following the discussion in the mailing list, can we close this issue?

**Comment by jimsch** [comment]
I am not quite ready to do so yet.

**Comment by jimsch** [comment]
I think that the mailing list answer is wrong, but I doubt I would be able to change opinions.
