### ISSUE TITLE
Encrypting the end-to-end CoAP Code?

### ISSUE THREAD

**Issue by emanjon** [core-wg/oscoap#149]
While reviewing the privacy considerations of OSCOAP and thinking about the HTTP-CoAP mapping, I started thinking about encrypting the actual end-to-end CoAP Code and replacing it with a small set of "dummy codes". Proxies have limited functionality when OSCOAP is used and should not need the full CoAP code when OSCOAP is used. 

Can we encrypt (and integrity protect) the actual end-to-end CoAP Code and use a small subsets of codes for the "outer" code field? The absolute minimum for the "outer" code would be something like:

  0.02 POST                with    payload
  2.04 (Changed)        with    payload

  0.01 GET                   without payload
  2.05 (Content)          with    payload

Where POST is used for non-observe, and GET is used for observe only. As far as I can see this have several strong benefits:

+ The privacy is increased.

+ The COSE object can almost always be sent in the payload. The only time it can not is the Observe Registration.

+ The HTTP CoAP-Code header is no longer necessary as the CoAP Code is sent inside the COSE object. The corresponding HTTP codes would be:

  POST
  200 OK

  GET
  200 OK

The disadvantage would be

- One byte additional message overhead, but given the benefits, it kinda seems worth it.

Would like feedback on this idea. Would this work or am I missing something?

**Comment by fpalombini** [comment]
If we add this, we should allow applications to optionally doing this, since there is a trade-off between encrypting the CoAP code (privacy sensitive) and allowing the proxies to process the messages (is the message safe/idempotent, can it be dropped). "Optionally" here means:
1. define how the Code is encrypted (probably 2 additional bytes, 1 for a marker, 1 for the Code itself in the plaintext)
2. server MUST allways be ready to process the message with Code encrypted (recognize the Code in the decrypted message; discard the "outer Code" and replace with the decrypted one). If the request contains an encrypted Code, MUST reply with an encrypted Code too.
3. the client MAY encrypt or not.

I would like to know what implementers think, what would be the best way to deal with "recognizing if the code is in the decrypted ciphertext or not"? First field with a marker afterward? last field with a marker before? Other ideas? @chrysn @jimsch @gunzter @t0bbe

**Comment by jimsch** [comment]
I do not have any coherent thoughts on this yet as I am still trying to work through some of the implications of this myself with looking at doing proxy work.  However some comments are:

1. The document probably needs to have a section on doing proxy work with descriptions of three different types of proxies:  coap2coap, coap2http, http2coap.
2.  It would be possible to use PATCH and iPATCH for the methods if you wanted to be able to distinguish idempotent distinctions.
3.  After the PATCH, iPATCH discussions on the list, it is clear that post the coap2http proxy, the http server is going to be unable to know what the method set by the coap client was as they are both going to map to the same HTTP method.  Additionally, the http2coap document discusses how different response codes are going to be changed in a way that cannot necessarily be deduced by the http client.
4.  I am not sure that there is any reason to make this optional.  There is nothing that says a coap2http server needs to have a Proxy-Uri option as it could do the mapping from a coap resource to an http resource silently.   I.e. a reverse proxy.   I would not expect this to be common, but it is possible and would be invisible to the client.

**Comment by emanjon** [comment]
Irrespectively of wether this functionality is added or not, this is a discussion we need to have. We should either encrypt or have a good answer why encryption is not possible.

**Comment by emanjon** [comment]
Trying to understand the "allowing the proxies to process the messages (is the message safe/idempotent, can it be dropped)", I do however see the problem with POST not being idempotent. I think simply using PUT as the outer field solves this.

- Safe: Responses to safe methods can be cached by the proxy, and OSCOAP cannot be cached anyway as the reponse is bound to request and the resource is hidded from the proxy anyway.

- Idempotent: Idempotent requests can be retried by the proxy without causing any problems. But this is true for all OSCOAP requests as the replay protection makes sure that the server only processes the request once. The suggestion to use POST could make a proxy unsure if a request could be resent. This could be fixed by simply replacing POST with PUT.

How does safe and idempotent affect a proxy's ability to determine "can it be dropped"?

**Comment by jimsch** [comment]
The implications that you are listing for Idempotent are somewhat worrying for me.  I would expect that a proxy would re-send a CON message and not send a NON message as long as there was not response and it had not exceeded the number of retries (for a coap endpoint).  I am not sure why you think that idempotent is a property that would change this.

**Comment by emanjon** [comment]
Agree, I think the only difference would be in the case of an coap2http proxy where the HTTP server gets an error and has to restart. Then I guess that the proxy would not know what to do with the POST request, while PUT always could be resent.

**Comment by jimsch** [comment]
Why would that be any different for an HTTP server than for a CoAP server?  Also how would the proxy ever know if the server has rebooted given that there may be another proxy between it and the final server?  I don't think that this can be distinguished if the server were to silently go belly up.   You might actually have a better chance of knowing this with a TCP connection since one could say that if the TCP connection goes down you are just going to error all requests and leave the problem to client where that is not possible with a UDP connection.

**Comment by emanjon** [comment]
My understanding is that:

A proxy not receiving a CoAP response would just resend the CoAP request, and it should not cause any problems even it the other endpoint (proxy ot server) got the same message twice.

A proxy not receiving a response to a HTTP POST would have to treat it as an error as it would not know if the non-idempotent request had been processed or not.

A proxy not receiving a response to a HTTP PUT could just resend it as soon as the other endpoint is back up again.

**Comment by emanjon** [comment]
Francesca: _"Optionally" here means: define how the Code is encrypted (probably 2 additional bytes, 1 for a marker, 1 for the Code itself in the plaintext)"_

I dont thing there is a need to make it optional and one byte should be enough. One solution would be to always encrypt the code (1 byte) and let the client decide what to put in the "outer field". Server always replaces "outer" code with "inner" code.

**Comment by jimsch** [comment]
@emanjon I think your understanding of "everything just works" for coap is probably not a correct assumption.  While it is true within reason, sending a PATCH to a server than then reboots may end up with the PATCH doing something bad if the server is not prepared to check that the ETAG with the request does not match what is going on.  We can ignore the coap side problem, but it still exists.  I was unaware until now that PUT is supposed to be idempotent, I will have to remember that.

Need to also deal with the server returning the error and allowing for to be remapped as well.  Problem occurs both directions

**Comment by emanjon** [comment]
Trying to summarize my understanding. REST methods comes in three classes:

1. idempotent, safe (e.g. GET)
2. idempotent, not safe (e.g. PUT)
3. not idempotent, not safe (e.g. POST)

With OSCOAP, a proxy can treat as methods as idempotent (because of replay protection). From a proxy perspective we therefore only get two classes:

1. idempotent, safe (e.g. GET)
2. idempotent, not safe (e.g. PUT)

So the subset {GET, PUT} should be enough for all proxy OSCOAP-REST processing.

Irrespectively of the code encryption question, I think there should be discussion of these things in the new proxy section.

**Comment by fpalombini** [comment]
(some updates from @gselander : f387ab3, 94cd04b, d773b7f to encrypt the code)
