### ISSUE TITLE
Definition of 'sid' and usage are potentially exclusive

### ISSUE THREAD

**Issue by jimsch** [core-wg/oscoap#15]
Section 5 - You have defined a 'sid' and said that it could be placed in the unprotected field, however you have also said that the unprotected field must be empty.  These statements are contradictory

**Comment by LudwigSeitz** [comment]
As per Christian Amsüss' message from 2017-01-05 there still seems to be confusing text in that section.

**Comment by fpalombini** [comment]
Answering both to @jimsch and @chrysn (https://mailarchive.ietf.org/arch/msg/core/t7dTEVvBuzp_a0ppCKlz3AYQRzg)

The point here is: when defining the 'sid' as a new COSE Header parameter, there is no reason related to security that would make this a "MUST be placed in the protected bucket", so instead it is a MAY. **But** when used in OSCOAP, the 'sid' is used in a way that it MUST be in the protected part, so the unprotected SHALL be empty. The 'sid' is analogous to 'kid' from this point of view, it is defined as a COSE parameter that MAY be unprotected, but is used protected.

**Comment by emanjon** [comment]
Multicast removed in branch v-02
