### ISSUE TITLE
Analyse any OSCOAP changes if TLS handshake is used instead of EDHOC

### ISSUE THREAD

**Issue by emanjon** [core-wg/oscoap#150]
The security AD wants to replace EDHOC with the TLS handshake unless EDHOC provides significant benefits. Should be analysed if such a solution leads to any changes to OSCOAP.

**Comment by emanjon** [comment]
I have made a quick analysis of this. Given that this happens, the only change to the OSCOAP specification that I see is that AES-CCM-16-64-128 should likely be MTI instead of AES-CCM-64-64-128. See reasoning below:

One functionality of EDHOC is to negotiate the OSCOAP AEAD and KDF. The cipher suites in TLS 1.3 are

              | TLS_AES_128_GCM_SHA256       | {0x13,0x01} |
              |                              |             |
              | TLS_AES_256_GCM_SHA384       | {0x13,0x02} |
              |                              |             |
              | TLS_CHACHA20_POLY1305_SHA256 | {0x13,0x03} |
              |                              |             |
              | TLS_AES_128_CCM_SHA256       | {0x13,0x04} |
              |                              |             |
              | TLS_AES_128_CCM_8_SHA256     | {0x13,0x05} |

which all use a 12 byte nonce.

Assuming that OSCOAP would adopt the same model as QUIC, the TLS cipher suites would be mapped to OSCOAP (i.e COSE) algorithms.

- The KDF part is easy

- The AEAD part is more complicated. COSE has the following AEAD algorithms:

      | A128GCM | 1     | AES-GCM mode w/ 128-bit key, 128-bit tag |

      | A256GCM | 3     | AES-GCM mode w/ 256-bit key, 128-bit tag |

      | ChaCha20/Poly1305 | 24    | ChaCha20/Poly1305 w/ 256-bit key,     |
      |                   |       | 128-bit tag                           |

      | AES-CCM-16-64-128  | 10    | 16 | 64  | 128 | AES-CCM mode        |
      |                    |       |    |     |     | 128-bit key, 64-bit |
      |                    |       |    |     |     | tag, 13-byte nonce  |
      |                    |       |    |     |     |                     |

      | AES-CCM-16-128-128 | 30    | 16 | 128 | 128 | AES-CCM mode        |
      |                    |       |    |     |     | 128-bit key,        |
      |                    |       |    |     |     | 128-bit tag,        |
      |                    |       |    |     |     | 13-byte nonce       |

      | AES-CCM-64-64-128  | 12    | 64 | 64  | 128 | AES-CCM mode        |
      |                    |       |    |     |     | 128-bit key, 64-bit |
      |                    |       |    |     |     | tag, 7-byte nonce   |
      |                    |       |    |     |     |                     |
      |                    |       |    |     |     |                     |

      | AES-CCM-64-128-128 | 32    | 64 | 128 | 128 | AES-CCM mode        |
      |                    |       |    |     |     | 128-bit key,        |
      |                    |       |    |     |     | 128-bit tag, 7-byte |
      |                    |       |    |     |     | nonce               |

I.e. the TLS handshake would not be able to differentiate between the two CCM variants (7 and 13 byte nonce). My thinking is that we would need to chose that the 5 TLS ciphersuites are either mapped to 

Alternative 1)

A128GCM
A256GCM
ChaCha20/Poly1305
AES-CCM-64-128-128
AES-CCM-64-64-128 

or 

Alternative 2)

A128GCM
A256GCM
ChaCha20/Poly1305
AES-CCM-16-128-128
AES-CCM-16-64-128

Given that CCM* (AES-CCM-16-64-128) needs to be supported somehow, I think the choice needs to be Alternative 2), and as a consequence I think that AES-CCM-16-64-128 should be MTI instead of AES-CCM-64-64-128.

(Replacing EDHOC with the TLS handshake would mean that several of the COSE algorithms are not negotiable)

**Comment by fpalombini** [comment]
Makes sense. I think we could implement this change right away (aka merge the pull request #153 ), since doing this change doesn't bring any major disadvantage as far as I can see. (adding 6B in memory for the nonce is not a bit problem)

**Comment by jimsch** [comment]
I am torn on which is the correct option.  The CCM TLS draft uses a 12 byte nonce with the top 4 bytes being implicit.  However, the answer for TLS 1.3 looks to be different as there is only an 8 byte (64-bit) nonce that is possible with the rest being constants derived from else where.  This would be closer to the 7-byte nonce of alt-1.  

That being said, it would be an arbitrary choice so I don't think I would have a preference.
