### ISSUE TITLE
Give short motivations for unencrypted fields?

### ISSUE THREAD

**Issue by emanjon** [core-wg/oscoap#154]
Maybe in the suggested coap2coap proxy handling section.

**Comment by fpalombini** [comment]
Assuming we do encrypt the code as you suggest in #149 , the only thing we do not encrypt without motivating why is the CoAP version:

     0                   1                   2                   3
     0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    |Ver| T |  TKL  |      Code     |          Message ID           |
    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    |   Token (if any, TKL bytes) ...
    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    |   Options (if any) ...
    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    |1 1 1 1 1 1 1 1|    Payload (if any) ...
    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
                          Figure 7: Message Format

We talk about Token, Message ID and Type in the Security Considerations (sec 11)

> The CoAP message layer, however, cannot be protected end-to-end through intermediary devices since the parameters Type and Message ID, as well as Token and Token Length may be changed by a proxy.

While options and payload have their own sections.

**Comment by jimsch** [comment]
Part of what we were talking with Thaler about was perhaps not worrying about the version number and doing something completely implicit with it based on payload type.  My mind does not work well enough to remember the details of what we were talking about.
