### ISSUE TITLE
Redundant length information in the the value of the Object-Security

### ISSUE THREAD

**Issue by emanjon** [core-wg/oscoap#156]
The encoding of the Object-Security Option in the OSCOAP Compression {#compression} section specifies that the length of the Partial IV and kid are explicitly encoded. This duplicates information in the OSCOAP messages as the total length of the Compressed COSE Object is already known.

- Is this really needed to simplify processing?
- Can we afford to waste 1 bytes in each request?
- Is it not possible to define a format/order that makes processing easy without wasting a byte?

**Comment by fpalombini** [comment]
It's only the kid size that adds 1B, since we cannot get rid of the first byte anyway, unless we go for something else than a bitmap.
How is the kid size retrieved if we get rid of that 1B?Assuming we know the Partial IV size, the total length does not give the kid size, but kid + ciphertext size.

**Comment by jimsch** [comment]
This is also going to be slightly problematic if you also look at what happens for group security where there are additional values included as well.

**Comment by fpalombini** [comment]
Not implemented.
