### ISSUE TITLE
Replace Sender IV and Recipient IV with a common Context IV 

### ISSUE THREAD

**Issue by emanjon** [core-wg/oscoap#157]
After reviewing the newly added section on "Nonce generation examples", reviewing the multicast draft, and thinking about ways to reduce the memory usage of OSCOAP I have come to the conclusion that I think the Sender IV and Recipient IV should be replaced with a common Context IV (in the Common Context) (I.e. a Fixed-Common field according to RFC5116). As each endpoint uses a unique key for encryption, a Fixed-Distinct field (RFC5116) is not necessary.

This significantly reduces memory usage or processing (depending on the implementation) especially in the case of multicast or an endpoint with many security contexts.

This simplifies the specification

This simplifies the implementation

This makes it easier to analyse the security.

The Context IV (Fixed field according to RFC5116) are used to protect against pre-computation and time-memory tradeoff attacks. A Common IV in the common context would fulfil this purpose.

(this was earlier submitted as pull request #152, opening an issue to make sure it is seen)

**Comment by jimsch** [comment]
I would disagree that it makes it easier to analyze the security as you can no longer treat all of the encryption from a single source to be independent of any other sources.  Knowing that the same IV is going to be used, even though the keys are different may open one to an attack.

**Comment by T0bbe** [comment]
I agree with Jim, it sounds a bit weakening to merge them into one.

**Comment by jimsch** [comment]
I will also note, that there is a space savings unless you are going to do an observe as the replay window detection code would not come into play - so that can be deferred for allocation until an observe is needed.  For the single case that may offset the space savings.

**Comment by jimsch** [comment]
Doing so might also cause a problem with a feature I would like to see restored at some point the future, but not before going to RFC, which is the ability to use different algorithms in each direction.  This means that there might be different lengths for the IVs in each direction.

**Comment by fpalombini** [comment]
With the recent changes (#173) on nonce generation, the nonce will be different for different senders (see section 5.1 Nonce for commit  ac1427b).  About the ability to use different sized IVs in each direction, you could have the same IV padded or truncated.

I don't understand what is the link with observe replay detection here, and how it is significant.

(We close the issue now, at commit 1a4c1384 including previous updates, but feel free to reopen it/continue the discussion)
