### ISSUE TITLE
 /.well-known resources should not use OSCOAP

### ISSUE THREAD

**Issue by LudwigSeitz** [core-wg/oscoap#158]
Since /.well-known is used to discover information, it is unlikely a client requesting one of these resources would have an OSCOAP context with the resource server. I would therefore suggest that we explicitly state that /.well-known resources should not be protected with OSCOAP.

**Comment by cabo** [comment]
`/.well-known` is not limited to `/.well-known/core`, but I'll use that as my example.

Indeed, `/.well-known/core` can be used for initial discovery, at a time when the client does not have a security association with the server.  But once there is a security association, the server can use `/.well-known/core` to disclose more information about that server for use within that security association.  This means a prohibition to use `/.well-known/core` with OSCOAP protection would be counter-productive, as some other mechanism would have to be used for secure resource discovery.

**Comment by LudwigSeitz** [comment]
Ok, let's weaken that then:  access to: `/.well-known` resources should not be denied by an OSCOAP-enabled server that receives a non-OSCOAP request to such resources.

**Comment by jimsch** [comment]
As long as you believe that what is returned can be an empty list I don't really have an objection to that.  However access control on what is released is of importance.

**Comment by T0bbe** [comment]
With discover information, do you mean to ping the resource or does it involve getting to know the resource's value? 

Maybe there exists an argument to distinguish between OSCOAP enabled resources and NON-OSCOAP resources?

**Comment by emanjon** [comment]
Given the discussion above, I does not feel like we can prohibit protection. I do not see how returning an empty list would help the the client more than an error message. It would in fact not even give the client information that protection is needed.
 
I think the current text ” The application decides the conditions for which OSCOAP is required.” is pretty good. The answer to weather protection is needed is much more complicated than just looking at the resource...

**Comment by emanjon** [comment]
Maybe some discussion and recommendations in the security considerations?

**Comment by gselander** [comment]
Agreed during phone meeting that current text is sufficient.
