### ISSUE TITLE
Generic section on proxy handling

### ISSUE THREAD

**Issue by jimsch** [core-wg/oscoap#159]
In the process of working on proxy code I have identified the following issues that need to be covered

1.  Double encryption - if you use OSCOAP both for E2E to the server and for authentication to the proxy then nested encryption would be required.  I would probably recommend a don't do this but needs to be discussed.
2.  Do we need a new media type for OSCOAP - needed to reply with content.  Could just use the COSE ones, but then the compression would need to be removed
3.  Define a new HTTP header parameter to carry OSCOAP for a GET.  Does the header need to be present for a POST or should content-type be used to do that indication?
4.  Are there any novel uses of or newly defined error codes that need to be treated differently when doing a coap2http mapping?  I can't think of any, but a review of the document for this is needed.

**Comment by emanjon** [comment]
1. Agree, we should probably not do this, but it needs to be discussed, and text added. If we would  specify that the Object-Security option is class E, would everything work, or would it cause problems? Have you analyzed it?

2. I don't think we need one. CoAP messages with Object-Security does not have an outer Accept or Content-Format options. I think we should specify that an HTTP client or HTTP server that wants to speak OSCOAP encodes Accept and/or Content-Format in the COSE Object. The Accept, Accept-Encoding, Content-Type, and Content-Encoding should not be present and ignored by the cross-proxy.

3. The current HTTP-CoAP Mapping section (suggested by Christian Amsüss on GitHub) suggests adding an Object-Security HTTP header. I think using this for all methods is the simplest solution.

4. Let's review...

**Comment by emanjon** [comment]
1. Thinking more, OSCOAP is not a good solution for protection client-proxy. The proxy could only verify that the real endpoint sent part of the packet, but all the CoAP fields that proxy cares about are unprotected. An attacker could still change Token, message ID, Uri-Host, etc. I don't think it should be done, and I don't want to spend time analysing and fixing problems that could arise. One problem is that the proxy would not no if OSCOAP was e2e or meant to be hbh but that the proxy does not have the context for some reason. Another problem is if there is a collision between the proxy Recipient ID and the server Recipient ID. I am starting to think that OSCOAP should treat the presence on an Object-Security Option in the unprotected message as an error.

**Comment by jimsch** [comment]
1.  I do not know that you have built the same solution as I envisioned.  However, there can always be a problem if the ids collide no matter what.  So this does not bother me.  I could easily write the code to allow for double wrapping of a message.  And what I am interested in protecting is access control not integrity of things like the token.  The Proxy-Uri would, in this case be part of the inner encrypted message so you actually have better security properties unless you are doing some type of traffic analysis on both sides of the proxy as you cannot know where actual endpoint of the client's request.  Changing things like the Uri-Host field or Token are just DOS attacks and can be done in far easier ways so uninteresting to me.

2.  I think that this may be the easiest way to signal to the HTTP recipient that the content is an OSCOAP message.  This would be needed for responses and for some requests such as PUT.  A long content is going to have to go into the body and tagged as OSCOAP.  A media-type is the easy way to do this.  The assumption would be that the server or client would be able to do the necessary coap 2 http translations in order to process the message.

3.  Will not work for long OSCOAP items as there is a header length limit.  Most of the time around 8K, but some contents can easily exceed this.

**Comment by emanjon** [comment]
The current suggestion in the appendix is to do a strict one-to-one mapping between CoAP and HTTP.

2. The suggestion from Christian is that the presence of an HTTP Object-Security Header indicates the use of OSCOAP. I do not see why this would not work.

3.  The current suggestion is that the HTTP Object-Security Header will be present but empty when the method allows payload.  I do not see why this would not work.

 GET /hc/coap://device.local/ HTTP/1.1
  Host: proxy.local
  CoAP-Code: 0.01
  Object-Security: CQcBE2H3D9KXsQ

[CoAP request -- Proxy to CoAP Server]

  GET /
  Uri-Host: device.local
  Object-Security: 09 07 01 13 61 f7 0f d2 97 b1 [binary]

[CoAP response -- CoAP Sever to Proxy]

  2.05 Content
  Object-Security: [empty]
  Payload: 00 31 d1 fc f6 70 fb 0c 1d d5 ... [binary]

[HTTP response -- Proxy to HTTP Client]

  HTTP/1.1 200 OK
  Object-Security: [empty]
  CoAP-Code: 2.05
  Body: 00 31 d1 fc f6 70 fb 0c 1d d5 ... [binary]

**Comment by jimsch** [comment]
It would definitely work.  The following would also work

GET /hc/coap://device.local/ HTTP/1.1
Host: proxy.local
CoAP-Code: 0.01
Object-Security: CQcBE2H3D9KXsQ

[CoAP request -- Proxy to CoAP Server]

GET /
Uri-Host: device.local
Object-Security: 09 07 01 13 61 f7 0f d2 97 b1 [binary]

[CoAP response -- CoAP Sever to Proxy]

2.05 Content
Content-Type: application/OSCOAP
Payload: 00 31 d1 fc f6 70 fb 0c 1d d5 ... [binary]

[HTTP response -- Proxy to HTTP Client]

HTTP/1.1 200 OK
Content-Type: application/OSCOAP; code=2.05

Body: 00 31 d1 fc f6 70 fb 0c 1d d5 ... [binary]

This allows for slightly better handling on the client as it can dispatch the content based on the content-type field to do the correct rendering rather than needing to figure that out based on the header field.  However, I doubt that I have a preference and think we should get browser people input.

**Comment by emanjon** [comment]
Good point, makes sense, lets discuss with them.

Would be nice but not crucial to to have it look the similar in both CoAP and HTTP. On the HTTP side, a few bytes message overhead is not that important. On the CoAP side Content-Format = X likely has more message overhead than an empty Object-Security option.

I don't think your earlier suggestion to "Could just use the COSE ones, but then the compression would need to be removed" works. I think there needs to be a difference between OSCOAP and a non-OSCOAP message with a COSE payload.

**Comment by jimsch** [comment]
I think that there may be a generic problem with the current IANA registration for application/cbor since there is no way to give an indication of what the parsed structure is supposed to represent.  One could use application/cose if one just wanted to separate normal cbor from OSCOAP cbor.  But then the problem still exists on what type of COSE as we are not using the content type field.  Generally a new or at least a specific type is better.  Could also use an OSCOAP header to indicate the structure type but that is not what I would really want to do.

**Comment by fpalombini** [comment]
Included in ac1427b and previous commits.
