### ISSUE TITLE
When is payload present - absent vs empty

### ISSUE THREAD

**Issue by jimsch** [core-wg/oscoap#16]
-00

Section 2 - We had a discussion at one point about using the code as the key for the question of payload being present in a document.  Specifically, one could do a put with an empty payload.  In that case the version of the Object-Security Option should be the one with payload. --- This is not done well in section 2 but is in section 6.2

**Comment by emanjon** [comment]
This needs to be fixed in B.1 and B.2. as well. At least 4 places that says "has payload".

**Comment by jimsch** [comment]
After trying to implement this, I think that i am regretting it.  There is no problem with the 0.* items.  However, it is not clear to me which of the 2.*, 3.* and so forth items permit and which do not permit it.  For example consider the possiblity that the "No Content" success code might be defined as having no content.  Is it sufficent to say that we just assume that everything other than the 0.* items could have content and go from there?

**Comment by fpalombini** [comment]
I went through the section 5.9, and I wrote down which options have optional, required or not allowed payload:

            +------+------------------------------+-------------+
            | Code | Description                  |   Payload   |
            +------+------------------------------+-------------+
            | 2.01 | Created                      |   optional  |
            | 2.02 | Deleted                      |   optional  |
            | 2.03 | Valid                        | not allowed |
            | 2.04 | Changed                      |   optional  |
            | 2.05 | Content                      |   required  |
            | 4.00 | Bad Request                  |   optional  | 
            | 4.01 | Unauthorized                 |   optional  |
            | 4.02 | Bad Option                   |   optional  |
            | 4.03 | Forbidden                    |   optional  |
            | 4.04 | Not Found                    |   optional  |
            | 4.05 | Method Not Allowed           |   optional  |
            | 4.06 | Not Acceptable               |   optional  |
            | 4.12 | Precondition Failed          |   optional  |
            | 4.13 | Request Entity Too Large     |   optional  |
            | 4.15 | Unsupported Content-Format   |   optional  |
            | 5.00 | Internal Server Error        |   optional  |
            | 5.01 | Not Implemented              |   optional  |
            | 5.02 | Bad Gateway                  |   optional  |
            | 5.03 | Service Unavailable          |   optional  |
            | 5.04 | Gateway Timeout              |   optional  |
            | 5.05 | Proxying Not Supported       |   optional  |
            +------+------------------------------+-------------+

For 2.xx, each response code specifies it in its own section.
As defined right now, all 4.xx and 5.xx allow payload: 

> The server SHOULD include a diagnostic payload under the conditions detailed in Section 5.5.2.

Also, section 12.1.2 very clearly states that documentation of a Response Code should specify whether payload is required, optional, or not allowed.

The only thing I can think of to add to the OSCOAP doc is that if an option does not specify it, it shall be assumed that the payload is optional. What do you think?

**Comment by jimsch** [comment]
But here is the problem.  Let's say a new item 2.99 (yes I know it is not legal) is defined.  It is defined as not having a content.  The code may be used by a resource that is using an existing library which will think that it should have content because that library does not know about the new item.  This is fine as long as there is no enforcement at any intermediary point, but otherwise it is a problem.  Would a proxy ever do this type of enforcement?
