### ISSUE TITLE
Typo. Request-Tag draft

### ISSUE THREAD

**Issue by T0bbe** [core-wg/oscoap#160]
**Chapter 3. The Request-Tag Option:** (first paragraph, third sentence)

_"The requests must be be..."_

Remove the extra _be_.

**Comment by emanjon** [comment]
This should be filed as an issue (or pull request) for the repeat-request draft
https://github.com/chrysn/repeat-request-tag

I have created a pull request that fixes this
https://github.com/chrysn/repeat-request-tag/pull/8/files
