### ISSUE TITLE
Replay protection of Observe Notifications

### ISSUE THREAD

**Issue by emanjon** [core-wg/oscoap#169]
The text in this section contradicts itself:

1. "If a persistently stored security context is to be used after reboot, then the node MUST NOT reuse a previous Sequence Number and MUST NOT accept previously accepted messages. Some ways to achieve this is described below:"

2. "A client MAY continue an ongoing observation after reboot using a stored security context. With Observe, the client can only verify the order of the notifications, as they may be delayed. If the client wants to synchronize with a server resource it MAY restart an observation."

Replay and delay are different things, while OSCOAP does just gives relative freshness for notifications it does always protect against replay. Following 2. an attacker might fool the client that something happens twice. I think the 1. is corrent and that the client either needs to store partial IVs in persistant storage or restart the observation.

**Comment by jimsch** [comment]
Please outline how you think that the attacker could do a replay.  i don't see this  I do believe that the MAY in the last sentence needs to be stronger however.  As in MUST.

**Comment by emanjon** [comment]
The full text is:

------------

To prevent reuse of the Nonce with the same key, or from accepting replayed messages, a node needs to handle the situation of suddenly losing sequence number and replay window state in RAM, e.g. as a result of a reboot.

After boot, a node MAY reject to use existing security contexts from before it booted and MAY establish a new security context with each party it communicates. However, establishing a fresh security context may have a non-negligible cost in terms of e.g. power consumption.

If a persistently stored security context is to be used after reboot, then the node MUST NOT reuse a previous Sequence Number and MUST NOT accept previously accepted messages. Some ways to achieve this is described below:

Replay Protection of Observe Notifications

A client MAY continue an ongoing observation after reboot using a stored security context. With Observe, the client can only verify the order of the notifications, as they may be delayed. If the client wants to synchronize with a server resource it MAY restart an observation.

------------

The assumption is that the client has parts of the security context stored in persistant memory but that some rapidly changing parts such as highest received partial IV in a notification is lost (the client no longer has a replay window). 

                       Client                Server
                          |                    |
                          |  GET /lock         |
                          |    Token: 0x4a     |   Registration
                          |  Observe: 0        |
                          +------------------->|
                          |                    |
                          |    2.05 Content    |
                          |    Token: 0x4a     |   Notification of
                          |  Partial IV: 12    |   the current state
                          |  Payload: 22.9 Cel |
                          |<-------------------+

Cleint Reboots and forgets highest recieved Partial IV

                          |                    |
                          |    2.05 Content    |
                          |    Token: 0x4a     |   Notification of
                          |  Partial IV: 12    |   the current state
                          |  Payload: 22.9 Cel |
                          |<-------------------+

Under these conditions I do see how the client would detect a replay.

**Comment by emanjon** [comment]
I think the "MUST NOT accept previously accepted messages" is correct and I think the client needs to chose between:

1. Store all recieved partial IVs in persistant storage
2. Restart the observation after a reboot

**Comment by jimsch** [comment]
No, the only think that needs to be done is to record the most recent partial IV received and only accept things which occur after that point.  Any observe before that should be considered to be old and rejected because it has been superseded

**Comment by emanjon** [comment]
But in case of a unplanned reboot the "most recent partial IV received" will be lost, unless they are stored in persistent memory. And storing every partial IV received in persistent memory would generally be costly ...

**Comment by gselander** [comment]
Addressed by recent update.
