### ISSUE TITLE
Observe freshness

### ISSUE THREAD

**Issue by emanjon** [core-wg/oscoap#170]
Should acknoledge that the freshness of observe notifications get worse and worse as time passes and give the recommendation to regularly restart the observation.

Also useful to write exactly what freshness garantuess OSCOAP gives.

**Comment by jimsch** [comment]
That text is part of the observe document.

**Comment by emanjon** [comment]
Ok, I read the observe document in detail to see what it says.

**Comment by gselander** [comment]
Addressed by recent updates.
