### ISSUE TITLE
Optimizing OSCOAP for group communication

### ISSUE THREAD

**Issue by emanjon** [core-wg/oscoap#173]
(This is not a new Issue but rather an analysis of several other issues).

The three suggested changes (#150, #155, and #157) are to replace AES-CCM-64-64-128 with AES-CCM-16-64-128 (13 bytes nonce instead of 7 bytes), generalize the bit flip mechanism by using the Sender ID of the endpoint that generated the Partial IV, and to have a common context IV. I think it makes sense to analyse these changes together.

While it has been verified that the current mechanisms work for group communication, we have not done analysis if the current mechanism makes the best trade-offs for group communication. Note that the changes are proposed to improve OSCOAP for group communication, but that the changes should be done in draft-ietf-core-object-security. My conclusion is that the changes together significantly reduces memory usage for multicast, significantly reduces message overhead for multicast, while keeping the wanted security level.

Did not get the formatting to work so I made a PDF instead:
https://drive.google.com/open?id=0B9LHkJUWxLqqNXp5REtOd3pnSTA

**Comment by emanjon** [comment]
New slightly updated version (Updates in yellow)
https://drive.google.com/open?id=0B9LHkJUWxLqqbTZ0OG9ZZWxURFk

**Comment by fpalombini** [comment]
Fixed by 1a4c1384 and previous.
