### ISSUE TITLE
Make Sequence numbers/partial IV for observe replay protection explicit in the security context

### ISSUE THREAD

**Issue by gselander** [core-wg/oscoap#174]
Section 6.4 states 
"In the case of Observe, the client’s Recipient Context contains the last received Partial IV for each active Observe registration" 

Make these "last received Partial IV for each active Observe registration" explicit in the Recipient Context definition.

**Comment by gselander** [comment]
Reopening this to give people a chance to comment.

**Comment by jimsch** [comment]
This gets a bit messy from the point of view of an implementer.  I would keep the partial IV as part of the observer context not as part of the security context.    That still may be ok from a description point of view as long as it does not move towards prescriptive language

**Comment by gselander** [comment]
The pedagogical point would be to have a name of the value being transported (Partial IV) different from the value it is compared with (Recipient Sequence Number). I renamed it "Notification Number" and moved it from the security context to the Observe processing. See  ab5ce42

Is that better?

**Comment by gselander** [comment]
The commit referenced above is wrong, should be  8a03f7f
(which also contains the starting point for the proxy section restructuring, sorry for the mix)

**Comment by gselander** [comment]
This issue was addressed with 8a03f7f
