### ISSUE TITLE
Edit HTTP-to_CoAP Proxy interaction.

### ISSUE THREAD

**Issue by jaimejim** [core-wg/oscoap#176]
The current version of the "HTTP-to-CoAP Proxy" provides an example of interaction from HTTP Client to HC to CoAP server. 

You could use the same mappings and notation as RFC8075 "Simple Form" (section 5.4.1.1) and append the URI of the HTTP host using "?target_uri={+tu}".

`
[HTTP request -- Before object security processing]
GET https://proxy.url/hc/?target_uri=coap://device.url HTTP/1.1
`

**Comment by gselander** [comment]
Ok, and same for the second message I assume:

POST https://proxy.url/hc/?target_uri=coap://device.local/ HTTP/1.1
