### ISSUE TITLE
Move flag byte into CoAP payload

### ISSUE THREAD

**Issue by gselander** [core-wg/oscoap#179]
The flag byte and kid was in the last revision moved to the Object-Security option to make use of the CoAP option length specification. To keep the flag with the rest of the COSE object, the flag byte should be moved back but the kid remain in the option.  The the kid indicator bit can now be removed from the flag byte. Examples needs to be rewritten.

**Comment by fpalombini** [comment]
We have a new proposal for saving 1 more byte from responses.
~~~~
                        +-+-+-+-+-+-+-+-+-------n-------+---1B---+------m-------+--------...
object-security value:  |     |k|h|  n  |   PartialIV   |  HintL |  ContextHint |   kid

CoAP payload: ciphertext and MAC
~~~~

Where:
k: bit presence for kid
h: bit presence for hint
n: size for Partial IV

This would create an overhead of:
2(option header + flag) + length(Partial IV) + length(kid) + MAC + 1(encrypted code) = at least 12B for requests and
1(option header) + MAC + 1(encrypted code) = at least 10B (we keep the optimization where the flag is only present if different than 0x00)

What do you think? ( @jimsch @chrysn )

**Comment by jimsch** [comment]
@fpalombini   What happens when I decide I need to add one more field to the compression?

**Comment by jimsch** [comment]
Example of field to be added is the counter signature(s)

**Comment by chrysn** [comment]
On Tue, Oct 17, 2017 at 01:46:36AM -0700, fpalombini wrote:
> What do you think? ( @jimsch @chrysn )

Looks good to me.

(If we were trying to shave off sub-byte parts we could think about
having everything that doesn't need the option's length determination
(PartialIV, HintL, ContextHint) move into the payload that we get
further with the 12 bytes of free length (we'd get along without using
the extended option length for more data), but I doubt that's worth the
additional implementation effort of having data spread out more.)

On Tue, Oct 17, 2017 at 04:23:00PM +0000, Jim Schaad wrote:
> @fpalombini   What happens when I decide I need to add one more field to the compression?

I suppose that's what the reserved three bits are for. Multicast might
need one or two of them, and whoever wants to use the last hopefully
defines an extension byte.

**Comment by jimsch** [comment]
@chrysn - yes but there is no length on the kid field so that there is no way to know where it is going to end so it cannot just be appended.

**Comment by chrysn** [comment]
On Tue, Oct 17, 2017 at 11:40:59AM -0700, Jim Schaad wrote:
> @chrysn - yes but there is no length on the kid field so that there is
> no way to know where it is going to end so it cannot just be appended.

I figure that iff the, say, first bit of the currently reserved bits is
set, there is another byte of flags, probably directly after the
original flag byte. (I thought I had seen something like that already in
multicast OSCOAP, but might be wrong.)

**Comment by gselander** [comment]
I'm not aware of any proposal for other flags besides one for counter-signature and potentially one specifically distinguishing uni/multicast. Which would leave one bit for the construction with a second flag byte, but I'd like to leave that out of this specification.

@jimsch - how are you with Christian's proposal:

>  (If we were trying to shave off sub-byte parts we could think about having everything that doesn't need the option's length determination (PartialIV, HintL, ContextHint) move into the payload that we get further with the 12 bytes of free length (we'd get along without using the extended option length for more data), but I doubt that's worth the additional implementation effort of having data spread out more.)

If I understand right you don't want flags in one place and length/value in another place -- in which case I suppose this is not an option?

Unless there are any other or repeated objections we make the text change today.

**Comment by jimsch** [comment]
My problem is not with adding bits to the flags, it is where does the value go - after kid does not work since the kid is implicit length.

**Comment by gselander** [comment]
How about adding fields before the kid? 

We could make the flag bits (except the first bit in each flag byte which indicates extensions) indicate present fields in reverse order if that is preferred.

~~~~
                        +-+-+-+-+-+-+-+-+-------n-------+---1B---+------m-------+--------...
object-security value:  |0|k|0|0|h|  n  |   PartialIV   |  HintL |  ContextHint |   kid

CoAP payload: ciphertext and MAC
~~~~
or with an extension flag byte defining a new field x, assuming all flagbits in the first flagbyte are taken:
~~~~
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-1B--+---x-----+-------n-------+---1B---+------m-------+--------...
 |1|k|0|0|h|  n  |0|0|0|0|0|0|0|x|  xL |  xValue |   PartialIV   |  HintL |  ContextHint |   kid


~~~~

**Comment by fpalombini** [comment]
@jimsch I would say the additional field (length followed by value) would go before the kid. kid must be last (we can specify that in the doc). The multicast document could easily specify that. That should not be a problem for implementations, or is it?

@gselander I don't think the order of the "presence"-bits in the flag matters, as long as it is set, so I wouldn't change it.

Adding an additional flag byte could be a solution... but I don't think we need it yet.
