### ISSUE TITLE
5-byte nonce length: nonce construction vs. algorithm's nonce length

### ISSUE THREAD

**Issue by chrysn** [core-wg/oscoap#182]
Reading the current version, I'm confused as to whether algorithms with nonce lengths <= 5 bytes:

Section 5.1 Nonce tells to pad Partial IV to 5 bytes, then pad generator sender ID to the rest of the nonce length. It does not say what should happen if the ID of the generator + 5 exceeds the nonce length, or even what to do with nonce lengths <= 5 bytes.

That wouldn't worry me (I'd read it as "algorithms must have at least 6 bytes nonces, and depending on your algorithm you'll need to limit your Sender IDs to that minus 5"), but Section 6.2 AEAD Nonce Uniqueness talks about maximum Sender Sequence Number being algorithm dependent (how so, if it's only used in 5-byte padded nonces anyway), and Section 11 referenced there states that the sequence number limit is "2^40 - 1, or any algorithm specific lower limit", which seems to imply that shorter-nonced algorithms are OK too.

Is this an editing issue from earlier versions that only had the leading flippy bit, or did I just get concepts wrong?

**Comment by jimsch** [comment]
GCM has a smaller than 2^40 limitation on the number of messages, it is closer to 2^32 (I forget the actual number off the top of my head and it's too early to care yet).   I don't know of any algorithms where the nonce length would not be much closer to the block size of the algorithm than 40 bits so the smaller than 5 case is probably not that interesting.

**Comment by chrysn** [comment]
Note from telco: Sounds like editorial leftovers; always nonces are 7 bytes or longer.

Leftovers seem to be in section 11 ("2^40") and 6.2 (sequence numbers are now always 0 to 2^40-1 because no algorithms can be supported that have shorter nonces anyway.

**Comment by vikram919** [comment]
@chrysn 

>It does not say what should happen if the ID of the generator + 5 exceeds the nonce length, or even what to do with nonce lengths <= 5 bytes 

As the draft say the ID is limited to 2^64-1 that means ID is limited to not more than 8 bytes. Am I right or did I understand it wrong?

**Comment by fpalombini** [comment]
@vikram919 That is correct for the (mandatory to implement) algorithm AES-CCM-16-64-128, which has a 13B nonce. There is no hard limit in the document for Sender ID. (If there is, please point it out as it is probably a mistake)

**Comment by chrysn** [comment]
With the (AFAIR decided) adoption of bytestring KIDs with Jim's XX-0000YYYY-ZZZZZZZZZZ encoding, nonces will practically need to be 56 bit (7 byte) long, for a 6-byte nonce can only have the zero-length byte string as a KID, and two KIDs are required for OSCOAP communication.

**Comment by jimsch** [comment]
True, but for the IoT world I don't think that is a problem, because you are not going to do really long messages.  It could be more interesting in the non IoT REST world, but there I think the default would be either GCM or ChaCha which both have 96 bit nonces..

**Comment by fpalombini** [comment]
@chrysn that's right, I will do that modification when we commit that change (so that the commits are consistent).

**Comment by chrysn** [comment]
The current version still says "2^40 - 1, or any algorithm specific lower limit" in the security considerations."; the "or any" part can't happen because algorithm nonce lengths need to be 5-plus-something bytes long.
