### ISSUE TITLE
Is "response SHOULD NOT contain a Partial IV" enough?

### ISSUE THREAD

**Issue by fpalombini** [core-wg/oscoap#185]
The document, as of now, specifies that Partial IV SHOULD NOT be present in responses without observe. (This refer to: https://core-wg.github.io/oscoap/draft-ietf-core-object-security.html#cose-object )

The processing for protecting and verifying responses, as of now, specifies that:
* if Observe -> use the Partial IV in the response
* if not Observe -> use Partial IV of the request

Should this part be changed to:
* if Partial IV present in the message -> use that Partial IV
* if not present -> use Partial IV of the request

**Comment by jimsch** [comment]
Need to read text, but this reflects what I wanted to see.

**Comment by fpalombini** [comment]
Sorry @jimsch, when you say "this" do you mean 

> if Partial IV present in the message -> use that Partial IV
> if not present -> use Partial IV of the request

That's not currently included (so no text about it yet).  The text right now is: 

> if Observe -> use the Partial IV in the response
> if not Observe -> use Partial IV of the request

**Comment by jimsch** [comment]
I was talking about the should change to
