### ISSUE TITLE
OSCORE version should be in the security context

### ISSUE THREAD

**Issue by fpalombini** [core-wg/oscoap#187]
(the one used in the external aad Section 5.3)

**Comment by jimsch** [comment]
Why?  I am not sure that this is the correct way to do the negotiation of this value.

**Comment by emanjon** [comment]
I don't think that should go into the context, I don't think anything need to be added.

**Comment by fpalombini** [comment]
The reason for this was that it is not specified where this value is stored in the node. But I see this is more of an implementation problem, so let's not add it.
