### ISSUE TITLE
This table is not valid anymore, remove it completely?

### ISSUE THREAD

**Issue by emanjon** [core-wg/oscoap#188]
+--------------------------+-----+-----+
|                          |  k  |  n  |
+--------------------------+-----+-----+
| Request                  |  1  | > 0 |
| Response without Observe |  0  |   0 |
| Response with Observe    |  0  | > 0 |
+--------------------------+-----+-----+

**Comment by fpalombini** [comment]
It is valid if we add a "as recommended" (or something similar), isn't it?
we still mandate kid to only be present in request and we recommend the partial iv not to be present in response without observe...
