### ISSUE TITLE
Context Hint only in serialization but not in COSE

### ISSUE THREAD

**Issue by chrysn** [core-wg/oscoap#190]
As I understand the relation between the OSCORE message and COSE, I think that the Context Hint should get an assigned COSE parameter name in the "COSE Header Parameters" registry. All other data that goes into or comes from the serialization passes through a COSE_Encrypt0 message, and I don't see why the Context Hint should be an exception.

Cc'ing @jimsch who should have an expert opinion on this :-)

**Comment by jimsch** [comment]
I would agree to that.  My first assumption was that it was the same thing as the group identifier but that may not be correct.

**Comment by gselander** [comment]
Context hint can be used a group identifier in the multicast setting, this is done so in Group OSCORE. In 6tisch Minimal security Context hint is used to transport EUI-64, which is the identifier used to find the pre-shared secret.

Yes, it is a correct remark that it probably should be defined for the uncompressed COSE.

**Comment by chrysn** [comment]
If there's a fitting header that already exists in COSE (like the group identifier), that's fine with me too.

**Comment by gselander** [comment]
We didn't find a suitable header, and, as mentioned, it is more generic than group identifier. So we should probably request a new entry in the "COSE Header Parameters" registry. Any objections to "Context Hint"?

**Comment by jimsch** [comment]
The use you are positing for 6tish seems to be more of a kid type usage, are you expecting to have both a kid and a EUI-64 identifier in the same message?

There is not currently a context hint, I would want to see a tighter definition on what it would be, but as I am not one of the Experts on that registry that is only a personal and not an expert opinion.

**Comment by gselander** [comment]
Previously 6tisch used EUI-64 concatenated with 0x00 or 0x01 as kid, in the latest version kid is just 0x00 or 0x01.

As I see it, in both group OSCORE and 6tisch this parameter is used as an extension to kid - as a means to find the kid in the relevant context; hence the term context hint. In these cases it need neither be unique (one reason for not calling it context identifier) nor be included in the external_aad. I believe there is a commonality here. In other use cases there may be other data serving the same purpose.
