### ISSUE TITLE
Why not use 2.04 outer code for observe responses?

### ISSUE THREAD

**Issue by fpalombini** [core-wg/oscoap#194]
After reading the observe doc one more time, I couldn't find anything explicitly forbidding to use 2.04 for observe notifications. Moreover, the following text in the observe rfc seems to suggest that 2.04 is a valid response code for observe:

>  If the server
>    returns a 2.xx response that includes an Observe Option as well, the
>    server has successfully added an entry with the client endpoint and
>    request token to the list of observers of the target resource, and
>    the client will be notified of changes to the resource state.

So, should we use 2.04 for observe responses too?

**Comment by fpalombini** [comment]
Or 2.05 for both observe/non-observe responses. ( as @chrysn suggested )

**Comment by chrysn** [comment]
The fewer things become special due to observation, the better. In the last tests, a client complained about the response codes the server used, and proxies suddenly dropping observations (which they can) are thus less likely to cause real trouble.

**Comment by fpalombini** [comment]
@ektrah what do you think? Do you see any problem with using 2.05 as a "dummy" code for responses both with and without observe?

**Comment by ektrah** [comment]
2.05 is not a valid response for POST requests.

**Comment by fpalombini** [comment]
Ok, that simplifies the choice :) thanks!

**Comment by chrysn** [comment]
The method descriptions say that a POST SHOULD have a 2.01 or 2.04 response (RFC7252 5.8.2) when successful, and FETCH (like GET) 2.03 or 2.05; that's not something proxies would be strict about.

The response code descriptions (sections 5.9.1.4f) say that 2.04 is only used with PUT/POST and 2.05 only with GET, but I wouldn't read those as normative precluding extensions. (However, there are strong statements about 2.04 not being cacheable).
