### ISSUE TITLE
Why can't CID be different between sender and recipient.

### ISSUE THREAD

**Issue by jimsch** [core-wg/oscoap#2]
Section 3.1 - I would think that you might be better off having the Cid be potentially different between the sender and receiver.  Currently the closest you get in EDHOC would be to use the nonces, which are too long to be used here.

**Comment by emanjon** [comment]
I think this might be a good idea, especially when used with EDHOC. The SessionIdentifier branch of EDHOC contain a specific (short) session identifier that would be perfect. I will make a study how and if this works with different use cases of OSCOAP (EDHOC, non-EDHOC, Group communication, Non-Group communication).

**Comment by emanjon** [comment]
I think this is a great idea. I looked into this and I think it works very well for all modes and deployment options, it might even simplify things. The current solution in EDHOC to derive random Cids makes them very large, and I keep hearing from radio people is that every single byte counts. Your idea would keep them minimal. I will wrote down a suggested update to OSCOAP and EDHOC before Chicago. Thanks for this great idea Jim.
