### ISSUE TITLE
single or double quotation marks (editorial)

### ISSUE THREAD

**Issue by emanjon** [core-wg/oscoap#200]
The document use both ' and ". E.g. "kid" and 'kid'

Should chose one alternative and use that. (e..g '' for single characters like 'x' and "" for strings like "dr who").

Purely editorial.

**Comment by fpalombini** [comment]
Should we try to be consistent with COSE? I think COSE uses '-' for (case sensitive) labels and "-" in general for (case non sensitive) literals.

**Comment by jimsch** [comment]
Go ask Sandy at the RFC Editor table what they would like the usage to be.  I did not have any style guide in mind when doing quoting.  I generally tried for single quotes for literals and double quotes for everything else but doubt that I am consistent.

**Comment by fpalombini** [comment]
I talked to Sandy and she said that there is no style guide. She just recommended to be consistent.
