### ISSUE TITLE
Reference to Code processing.

### ISSUE THREAD

**Issue by T0bbe** [core-wg/oscoap#204]
The encryption of Code (and adding the fake Code to the header) is not mentioned during the sub chapter "7.1. Verifying the Request". To help a reader, a clear reference to 4.3 would be helpful.

**Comment by fpalombini** [comment]
I am not sure I understand, we do not do encryption of code during verification... we do discard the outer one and write the right one from the ciphertext to the coap message, as specified. Is anything missing? How should we reference 4.3 in this case?

**Comment by T0bbe** [comment]
Sorry, I mentioned the wrong sub chapter, I meant to write: 7.1 "Protecting the Request".
