### ISSUE TITLE
Make the processing which require Echo or Request-Tag optional

### ISSUE THREAD

**Issue by gselander** [core-wg/oscoap#206]
Also, make the reference to ERT informational.

**Comment by gselander** [comment]
The use of Request-Tag with Block1 is mandatory -- should we move this text to ERT? Alternatively not possible to make processing optional and make reference of ERT informational.

(Some typos w.r.t. echo are fixed in 97a69dd)

**Comment by jimsch** [comment]
No you cannot really move that text to ERT because it is something that a OSCORE developer needs to know.  It is not an absolute manditory, but since it is going to be a normative requirement (even if it is a MUST do in the following circumstances) then you cannot really make it informational

**Comment by gselander** [comment]
Note first that this is just to avoid potential dependencies in RFC editor processing.

Echo is not normatively used so that is no problem. For Request-Tag, the processing is defined in the context of Block processing. Since ERT is an update of RFC7959 (Block), an implementation that supports block should update to ERT. Since the normative statments in OSCORE directly reference  processing in ERT, why could we not just take out the normative statements here and simply note that there is an upcoming update of Block - informationally reference ERT?

**Comment by gselander** [comment]
Here is an attempt: d58a8de

Unless someone objects I will  close the issue

**Comment by LudwigSeitz** [comment]
I double checked, there still seems to be remenants of ERT being normative:

In 3.2
>  ...The replay window type and size is used by the client in the processing of the Request-Tag I-D.ietf-core-echo-request-tag]. "

and in 4.2.3.2.2

> To allow multiple concurrent request operations to the same server (not only same resource), a CoAP proxy SHOULD follow the Request-Tag processing specified in Section 3.3.2 of [I-D.ietf-core-echo-request-tag].
