### ISSUE TITLE
Option table: Object-Security missing

### ISSUE THREAD

**Issue by chrysn** [core-wg/oscoap#210]
In -06, Object-Security is described using the old template (C/U/N/R but no E/I/U columns) in section 2 and not listed in Figure 4, even though "new options are asked to state whether they are E/I/U", and Object-Security is not really the default "E".

I find that omission strangely suiting, as the document does not yet say whether and how one could use OSCORE to protect communication with a proxy when communication is also protected end-to-end.

I therefore suggest we leave the text as it is and close this as "won't fix" to be taken up if and when something is written on that as suggested in #132.

**Comment by jimsch** [comment]
I am not sure what you think you would be protected when talking to the proxy.  The fields that are left in the open would still need to be open.  I assume you mean that you want to authenticate to the proxy while doing end-to-end protection.

My code would not currently be able to produce this on the client side, but you can just nest without any problems.
