### ISSUE TITLE
OSCORE support for No-response option(?)

### ISSUE THREAD

**Issue by gselander** [core-wg/oscoap#214]
Esko's review highlighted the No-response option (RFC 7967). Why is this an informational RFC, not a Proposed Standard? Should we define OSCORE processing?

**Comment by cabo** [comment]
Option registrations don't need to be PS.  In this case, the WG had issues completely agreeing that the solution was the right way to handle the problem presented, so we went for encouraging individual submission (this is not an IETF stream document).

Would it make sense to have OSCORE processing?  If it doesn't require major surgery, I would prefer to support it.

**Comment by gselander** [comment]
I updated the text: c93ac82

Unfortunately, I don't think the procedure works since the application will not know if OSCORE received both Inner and Outer No-Response or only received an Inner option. In both cases, there will be a No-Response option forwarded to the Request/Response layer.

**Comment by gselander** [comment]
OK, it works assuming the application is made aware. So, now we have specified the use of Inner and Outer No-response, and indicated how applications can handle proxies which are unaware of No-Response. I close the issue, reopen if there is something missing.
