### ISSUE TITLE
 see Appendix C for implementation notes for this encoding).

### ISSUE THREAD

**Issue by emanjon** [core-wg/oscoap#218]
- Appendix C is test vectors and does not contain implementation notes for this encoding (I cannot find it anywhere else either). The reference "Appendix C" should be a xml/kramdown reference to a defined anchor.

**Comment by fpalombini** [comment]
It's "see {{RFC7515}} Appendix C" right now, I guess we can change that to "see Appendix C of {{RFC7515}}" to make that more clear. I do not recommend adding a md ref to Appendix C of RFC 7515 since we do not have direct ref to sections of external documents either.

**Comment by emanjon** [comment]
My fault, I missed 7515
