### ISSUE TITLE
CoAP Content-Formats Registry

### ISSUE THREAD

**Issue by emanjon** [core-wg/oscoap#221]
Opening an issue on this so we don't forget it.

Carsten commented in his review that while a CoAP Content-Format is not needed on-the-wire (and would cause increased overhead), some applications use Content-Format for other use cases. Need to do IANA registration and write some short text about this. I.e. SHALL NOT/SHOULD NOT appear on wire. Meta data to process the ciphertext is in the Option value, etc..

**Comment by emanjon** [comment]
- The text for the different IANA sections should be aligned.

- Content-format should be talked about in the document, now it just pops up in the IANA section. Needs to describe that this is not to be used on the wire.

- Do we need to request assignment in the 0-255 range when this is not even used on the wire? I assume we can live with 2 bytes.

**Comment by ektrah** [comment]
Is the content meaningful if not accompanied by the OSCORE Option or is it always incomplete without?

👍  for 2 bytes.

**Comment by emanjon** [comment]
Done in recent commits.

**Comment by ektrah** [comment]
https://github.com/core-wg/oscoap/commit/ca5982344d5df12ff81a1faa802ccb3b56f5ab48

> The OSCORE body cannot be understood without the OSCORE header field value and the security context.

In that case I can't imagine any use case where an applications might want to use the content-format. If an application wants to use the content not on-the-wire, it would likely always need to create its own data format that combines the information in the OSCORE option and body.

**Comment by emanjon** [comment]
The text you copied are for the content-type which are on the wire. The Content-Format was requested by @cabo, let's reopen the issue and discuss.
