### ISSUE TITLE
Including kid_context in key derivation

### ISSUE THREAD

**Issue by gselander** [core-wg/oscoap#227]
In some applications, e.g. group communications, uniqueness of Sender IDs is not sufficient. This is currently solved with changing the 'info' structure or modifying the 'id'-parameter used in the OSCORE key derivation. One straightforward solution is to include the kid_context in the 'info' structure. Since this is useful in several applications, we propose to this change directly in the OSCORE specification.

**Comment by jimsch** [comment]
It might be better to have two ids if you are going to just define it here rather than doing  a concatenate operation

**Comment by gselander** [comment]
I made two first commits to address this issue:
https://github.com/core-wg/oscoap/commit/a32f5e5ba
https://github.com/core-wg/oscoap/commit/3ddd07fe

The new definition is in:
https://core-wg.github.io/oscoap/draft-ietf-core-object-security.html#rfc.section.3.2.1

@jimsch : Was this what you had in mind?

**Comment by jimsch** [comment]
yes
