### ISSUE TITLE
Separate header parameter for transporting Master Salt

### ISSUE THREAD

**Issue by gselander** [core-wg/oscoap#228]
The kid_context has been used in different applications either as an extended identifier of the client, or as a container for a Master Salt. You may want to use these independently, e.g. in order to reuse a master secret in a setting where both sender ID and identifier of the client are fixed. The proposed solution is to have a separate header parameter (flag bit 6) to indicate the presence of a Master Salt.

@jimsch: Could we use the COSE parameter -20 for this or do we need to define a new common header parameter?

**Comment by jimsch** [comment]
I don't understand why you are doing with flag bit 6, the salt should be set at the time of key derivation and then never changed.  sending it in a message does not make any sense because that would require doing a new key derivation and we have already thrown away the input needed for that.

**Comment by gselander** [comment]
One example: A device is provisioned with PSK from factory, commissioned in one network using the PSK as the master secret and then recommissioned in another network again using the PSK as the master secret. The procedure for using the PSK provided at purchase of the device needs to be the same in both deployments for usability reasons. Another example is if multiple clients are set up to talk to the same device using the PSK of the device. Appendix B2 sketches one way of using a transported master salt. 

You are right that In these cases the input material can't be thrown away. We mention the case of deriving keys multiple times in section 3.1:
"An endpoint may free up memory by not storing the Common IV, Sender Key, and Recipient Key, deriving them from the Master Key and Master Salt when needed."

**Comment by jimsch** [comment]
What a really really bad idea.  This is so prone to badness that I would never want to see it deployed.  Even worse is the idea of doing it as part of a normal message flow.  If you do this it needs to be done as a completely separate operation and not as part of sending a normal message.

No you cannot use a small negative number such as -20 for this based on the current definitions in COSE.

**Comment by gselander** [comment]
All aspects of transport of Master Salt are now reverted and Appendix B2 is rewritten. Further comments are welcome.
