### ISSUE TITLE
request_piv for cancellations (Jim review)

### ISSUE THREAD

**Issue by fpalombini** [core-wg/oscoap#231]
In section 5.4 you have the text

request_piv: contains the value of the 'Partial IV' in the COSE object of the request (see Section 5), with one exception: in case of protection or verification of Observe cancellations, the request_piv contains the value of the 'Partial IV' in the COSE object of the corresponding registration (see Section 4.1.3.5.1).

I am unclear how/why this is different for observations.   A cancelation is
a message, so the IV is the request.  A re-registration is a request message, any response would correspond to that request.  The only interesting question has to do with updating the MID on a re-registration but not how PIVs work for this field.

**Comment by jimsch** [comment]
Another case to make sure that works

Client - please cancel my observation
Server - I don't have an observation for you, but sure I am willing to tell you I canceled it.
*  What request PIV would I use in the AAD?

**Comment by fpalombini** [comment]
Yes, the verification of cancellation would fail since the server does not have the initial registration's partial iv saved, if it does not have the observation stored. So OSCORE would fail, which is not right.

We have reverted to previous version (request_piv is not exception for cancellations) in c94314321 , but we want to add some security considerations about Observe and cancellations before closing this issue.
