### ISSUE TITLE
flagbyte registry (Jim review)

### ISSUE THREAD

**Issue by fpalombini** [core-wg/oscoap#232]
Section 6.1 - Is a registry needed for the leading byte of compression?
Behavior if bits 0, 1, or 2 is set in the flags byte on decode?

**Comment by fpalombini** [comment]
I am now writing down a proposal text for this, and I am considering the policy for this registry. Is "Expert review" good enough? Should it be Specification required? Considering that the registry ranges 0 to 7, and all the values are either assigned or reserved... 

I think I lean forward [Expert review](https://tools.ietf.org/html/rfc8126#section-4.5), anyone has a different opinion?

**Comment by jimsch** [comment]
I think that this should require a standards track document if there are only 3 bits.  If there are more bits and it is documented how those bits are accessed then Expert review should be fine.

**Comment by fpalombini** [comment]
Right now we have 5 bits assigned in OSCORE, of the 3 left 2 will be assigned in OSCORE Groupcomm, and the last one should be the "extend the flag byte", but that one is not specified anywhere yet... But I assume that should extend the existing registry? is that possible? Or will that doc have to define a new "extended OSCORE flag registry"? this second registry could have expert review, while the first one has standard...

**Comment by fpalombini** [comment]
Ok, so maybe the right thing to do  in OSCORE is:

- assign 0-4
- standard action policy for the rest

and in other doc:

- group oscore assigns 5-6
- write a very short doc for extending the flag byte: uses this bit left and creates a new registry with expert review only (this is not only for 8 additional bits, but for as many bytes as one wants)

I will commit a proposal for this soon.

**Comment by fpalombini** [comment]
After a quick chat with Jim: new proposal: increase the range to 64 bits, reserve 8th bit, change the policy to expert review. Text coming...

**Comment by fpalombini** [comment]
closing this, will reopen if need be
