### ISSUE TITLE
HKDF: id text

### ISSUE THREAD

**Issue by chrysn** [core-wg/oscoap#240]
In the id description of the HKDF, it says that "The encoding is described in Section 5.". The sender or recipient ID is a byte string all along and encoded in CBOR as a bstr; what is there to be encoded, so what should I look for in Section 5 here?

(To me, this appears like a left-over line from when sender/recipient IDs were numeric.)

**Comment by fpalombini** [comment]
Yes that is exactly correct, thanks for pointing it out! Will remove.
