### ISSUE TITLE
Add ref. to OSCORE processing specification

### ISSUE THREAD

**Issue by gselander** [core-wg/oscoap#243]
The IANA registry for CoAP options should have a reference to where the OSCORE processing of that option is defined. Add text in the IANA section of OSCORE.

**Comment by gselander** [comment]
Proposed solution after discussing with @ektrah: 53a6e20

**Comment by gselander** [comment]
And updated in 8cf1601c and fe6264e

**Comment by fpalombini** [comment]
Thanks for this, it was needed.

Question for you and @ektrah : why not add another column, with a name such as "OSCORE Processing"? Is that really that much harder (IANA-wise) than change all the entries of the existing one so far?

**Comment by ektrah** [comment]
Yes, changing the registry itself is a bit harder.

I expect that future option specifications will include OSCORE processing, so the new column would only be needed for the existing options. Some already have two references, so adding another one is probably not a big deal.

My initial idea was to record the option class in the registry (E, I, U), but apparently it’s not that simple for all options.

**Comment by fpalombini** [comment]
> Yes, changing the registry itself is a bit harder.

Ok then, let's stick with this.

@gselander:

> Proposed solution after discussing with @ektrah: 53a6e20

That commit number is wrong, and you probably meant ed52ce4

Edit: nevermind, I missed one commit.

Closing it now :)
