### ISSUE TITLE
error messages

### ISSUE THREAD

**Issue by fpalombini** [core-wg/oscoap#254]
Rikard noted: in certain cases clients cannot distinguish between error messages from OSCORE processing and from CoAP processing; e.g. a 4.02 error message could be caused by "failure to decompress" or "option not recognized". A client cannot assume either of these.

In D.5.3. Error and Signaling Messages it might be worth noting this, as the result from "OSCORE was not decoded properly" and "the server does not accept OSCORE" could lead to different results in the client.

**Comment by emanjon** [comment]
The appendix "Error and Signaling Messages" should discuss shortly that the type of error message might reveal information about which (and how many) security contexts exists at the server and that a server may want to answer with the same error message or not respond at all.
