### ISSUE TITLE
Reference 5952 for canonical IPv6 address

### ISSUE THREAD

**Issue by jimsch** [core-wg/oscoap#26]
There needs to be a canonical way to represent IPv6 addresses in the document for authentication.  The current way to do this is https://tools.ietf.org/html/rfc5952

**Comment by jimsch** [comment]
After trying to deal with this even longer, the better answer might be to just forbid the use of IP addresses and require use use of a name.  Although I do worry about a proxy converting a name to a FQDN as this would mess things up as well.

**Comment by fpalombini** [comment]
This sounds like the best thing to do, right now. Also considering that CoAP may run over foo (and not use IP).
