### ISSUE TITLE
Typo in 5.4  option: 0x (0 bytes)

### ISSUE THREAD

**Issue by LudwigSeitz** [core-wg/oscoap#262]
In section 5.4 we present an example of the AAD, including a bullet reading like this:
"options: 0x (0 bytes)"

It feels like the '0x' part is a typo, otherwise I don't understand what it means and it should be clarified.

**Comment by fpalombini** [comment]
It's not a typo, it is the beginning of a 0-length hex byte string, a bit like h'' in CBOR bstr.
It is a choice because if we wrote "options: (0 bytes)" it would have felt like we forgot something.

Do you have a proposal? Couldn't find a better way to express that.
