### ISSUE TITLE
Clarify duplicate options

### ISSUE THREAD

**Issue by fpalombini** [core-wg/oscoap#28]
#18 and #19 depend on this

**Comment by jimsch** [comment]
I am not sure that I agree that the correct marker for the block options is 'd*'  'e*' might be a better answer as the two sets of values are completely distinct.  This is why I ignored it and addressed it as a separate paragraph in my writeup

**Comment by fpalombini** [comment]
I think it is in the middle, from a "theoretical" point of view you can have this option present in the message encrypted and unencrypted (which is why I labeled it modified-d), but from a "CoAP processing" point of view, it's probably closer to modified-e. I will change this.

**Comment by fpalombini** [comment]
Dealt with this in 24de5da5
