### ISSUE TITLE
Make algorith be entity specific

### ISSUE THREAD

**Issue by jimsch** [core-wg/oscoap#3]
Section 3.1 - In principle, the algorithm could be different between the sender and receiver context.  I am not sure that I would disallow this in defining your context structure.

**Comment by jimsch** [comment]
An example of where this might be done is to use a 64-bit tag in one direction but a 128-bit tag in the other direction to get a greater margin of security on the authentication.

**Comment by fpalombini** [comment]
We would rather not do this for simplicity reasons, unless there is a really good case for it.
