### ISSUE TITLE
Use of just expand phase makes things hard in some cases

### ISSUE THREAD

**Issue by jimsch** [core-wg/oscoap#31]
Not all crypto libraries expose just the expand phase of HKDF.  The library that I am working with (BouncyCastle) appears to only expose the entire HKDF code and not the two extract and expand phases.  While it is not hard to implement the expand phase, esp given that none of the values are more than one hash length long, it maybe better to use both phases.

**Comment by gselander** [comment]
Is it common that only the composed HKDF is available?

The assumption in the draft is that we only need to run HKDF expand, in which case HKDF extract would be redundant.  We would need to specify the salt (which may be a string of zeroes). If someone want to implement from scratch the extract step would be an unnecessary step for them.

Considering that the expand step most likely always will be one round, we propose to specify the HKDF-expand derivation operation directly in the draft: HMAC(master_secret, info || 0x01). In that case, the implementer has two choices, find a library or call HMAC once. 

Would that be sufficient?

**Comment by gselander** [comment]
I meant replaced HKDF-Expand with HKDF.
