### ISSUE TITLE
Guidence needed on how to handle different types of error conditions

### ISSUE THREAD

**Issue by jimsch** [core-wg/oscoap#33]
In going through the implementations, I have found the following locations (so far) that I think need to have either better or different error behavior than is currently called for in the document.  As an example, the current code for case 2 below is defined as drop the message.  For the CON world, this means that the client is going to resend the message until it times out.  This means that the same message is going to be process and dropped multiple times without the client getting any feedback on what the problem is and how to fix it.  

The problem with some of the messages in the second set is that dropping means that the client needs to do some type of re-start from scratch, but is not going to do a resend of the request by default behavior since the layer that does automatic retries of requests has been satisfied.  A non-security message that is clean has been received and satisfied that layer, but it was rejected at the security layer.  On the other hand if the security layer does a resend of the same message it is going to run into a potential problem with the replay window.  Note that this is not a problem for the non-security case with idempotent requests but could be with non-idempotent requests.  In the latter cases it would be not uncommon to try and reproduce a cached response to the request rather than re-generating the response from scratch.  This would seem to be the appropriated behavior for the security cases as well but is not covered in the replay window descriptions.  DTLS has the concept of caching and re-sending the last flight of messages in response to a re-transmit.  I think that this is going to need to be thought out and documented.  

Errors may be different for the cases of CON and NON.

Client --> Server
   1) Message required to have security and doesn't
       - 4.01 "Request requires security"
   2) COSE message fails to decode
       - No Body - 4.02
       - W/ Body
   3) Cannot Find Context
   4) Fails to decrypt/validate crypto
   5) Internal message is malformed
   6) Hit in the replay window
      - Same as last message processed
      - Else

Server --> Client
   1) COSE message fails to decode
   2) Cannot Find Context (Multi-cast)
   3) Fails to decrypt/validate crypto
   4) Internal message is malformed
   5) Hit in the replay window
      - Same as last message processed
      - Else

**Comment by fpalombini** [comment]
Thank you @jimsch , i went ahead and made a proposal for error handling in these situations. I tried to cover everything, feel free to review.

**Comment by fpalombini** [comment]
Oh and I realized by writing that there exist no CoAP error messages from client to server (duh), so I propose that the client sends an empty ACK back in case of CON even if it fails any step. I think client can retry, and we don't want to spend the server resources retransmitting without reason.
