### ISSUE TITLE
OSCOAP needs to have an integrity only mode

### ISSUE THREAD

**Issue by jimsch** [core-wg/oscoap#34]
I would really like to see a signature only version of OSCOAP.   I don't care about a MAC only version as I believe this is better served by doing AEAD.  However, a sign only mode with TLS provides both the needed end-to-end integrity with passive confidentiality checking.  It supports the requested mode of being able to observe the contents but not alter them.  This has been raised a couple of times.

**Comment by gselander** [comment]
Since we have both the public keys and the bits in the flagbyte described in the multicast OSCOAP draft, it was straightforward to include this functionality there, see 

https://ericssonresearch.github.io/Multicast-OSCOAP/#rfc.appendix.D

@jimsch : please check if this is what you had in mind.

**Comment by gselander** [comment]
I realize now there is an error in Appendix D - there should not be any encryption just plain signature.

**Comment by fpalombini** [comment]
Moved to multicast
