### ISSUE TITLE
Issues with building COAP messages 

### ISSUE THREAD

**Issue by jimsch** [core-wg/oscoap#38]
These may need to be separated into different issues as some point

    If this is going to be used, then Appendix B should be part of the main document.

    Appendix B - Is there only a single address that this would be posted to? Why not post to uri-path: "resource-name/edhoc/"

    Appendix B - how do I combine this with an authentication tag.

    Appendix B - how do I combine this with an OSCON rather than an OSCOAP message?

    Appendix B - how does the OSCOAP post know which location to link to if there are multiple possible outstanding edhoc destinations or sessions?

**Comment by fpalombini** [comment]
I think this issue does belong to EDHOC (and has in part been fixed already). Please feel free to reopen it there.
