### ISSUE TITLE
Clarify pre-established parameters and default values

### ISSUE THREAD

**Issue by LudwigSeitz** [core-wg/oscoap#42]
As per Christian Amsüss' message from 2017-01-04 we should clarify what is meant in section 3.2 with the default values given for parameters that "SHALL" be pre-established.

My take is that this needs to be clarified as suggested by Jim Schaad, i.e. that the defaults are actually MTI's. Thus "Default" is a minomer here.

**Comment by fpalombini** [comment]
Adding the reference to the said mail from Christian: https://mailarchive.ietf.org/arch/msg/core/328ja7ggGRLuvfpb2XIO_iMhNjg
And Jim's response: https://mailarchive.ietf.org/arch/msg/core/rG1EH_qBy3s6NRxDP2-eoyDnjs0
