### ISSUE TITLE
Security considerations about security context reuse in case of reset

### ISSUE THREAD

**Issue by gselander** [core-wg/oscoap#48]
Per Christian's comment 170104, provide guidance about security context reuse in case of reset and in general about use of PSK in embedded devices in case of reset

**Comment by cabo** [comment]
Can you provide a reference to what specific comment you mean?
(Hint: mailing list messages have those references in the header; this can be shown e.g. in Apple Mail by just configuring the mail reader to show the Archived-At header.)

**Comment by cabo** [comment]
Oh, found it (?):
Archived-At: <https://mailarchive.ietf.org/arch/msg/core/328ja7ggGRLuvfpb2XIO_iMhNjg>
Archived-At: <https://mailarchive.ietf.org/arch/msg/core/t7dTEVvBuzp_a0ppCKlz3AYQRzg>

**Comment by gselander** [comment]
Sorry, yes, the comment on replay protection here:
https://mailarchive.ietf.org/arch/msg/core/328ja7ggGRLuvfpb2XIO_iMhNjg
