### ISSUE TITLE
Section 3.2.1 - clarify that out_len is a bit count not a byte count

### ISSUE THREAD

**Issue by jimsch** [core-wg/oscoap#50]
There is a difference between output_length and out_len in the one is in bytes and one is in bits.  This should be highlighted in the document.  The descriptive text following output_length says that it is the size of the key/IV in bits, however the description in the paragraph defining output_length says that it is bytes.

**Comment by fpalombini** [comment]
> The descriptive text following output_length says that it is the size of the key/IV in bits, however the description in the paragraph defining output_length says that it is bytes.

You are right, we will fix the example.

> There is a difference between output_length and out_len in the one is in bytes and one is in bits. 

We did intend "in bytes" both for output_length and out_len. We will write that explicitly for out_len.

**Comment by jimsch** [comment]
It is normal to specify keys and IVs in bit lengths.  Please keep that.

**Comment by emanjon** [comment]
After aligning with HKDF and adressing the issues that people do not want two different variables. The variable "L" is now a byte count (as specified by HKDF).
