### ISSUE TITLE
Is the guidence on MaxAge correct?

### ISSUE THREAD

**Issue by jimsch** [core-wg/oscoap#51]
Based on my (potentially poor) understanding of caching responses, given that the OSCOAP value is included in the cache key computation, for a GET operation the response would never be cached as each OSCOAP value would be statistically likely to be unique.  This would indicate that the MaxAge value would only need to be set to zero for non GET operations.

Additionally, it would be nice include some guidance text for the SHOULD - i.e. this is normally going to be MUST, but under what circumstances does it make sense not to force the option to be set.

**Comment by fpalombini** [comment]
> Based on my (potentially poor) understanding of caching responses, given that the OSCOAP value is included in the cache key computation, for a GET operation the response would never be cached as each OSCOAP value would be statistically likely to be unique. This would indicate that the MaxAge value would only need to be set to zero for non GET operations.

More exactly, even if the value is cached, the proxy will never forward the cached value, but yes.

We do have some doubts here about computing the cache key: more precisely, we couldn't find anything in the CoAP spec about the payload being used in the cache key computation. If the payload is not used for cache key computation, then Errors would get cached and re-used for different clients, unless MaxAge is set to 0 (in the [security requirements draft](https://tools.ietf.org/html/draft-hartke-core-e2e-security-reqs-02#section-2.2.2) it was specified that 2.05 response and error responses are cacheable). @ektrah is that the case? For this reason we are thinking of changing the SHOULD to MUST.

**Comment by ektrah** [comment]
The request payload is part of the cache key.

**Comment by LudwigSeitz** [comment]
@ektrah:
I have been scouring the CoAP draft for any mention of this, but have been unable to find one, could you give us a hint?

**Comment by cabo** [comment]
Interesting.  It seems you found the first errata for RFC 7252...

**Comment by LudwigSeitz** [comment]
Sorry I meant CoAP RFC, not draft.

**Comment by ektrah** [comment]
To be precise, the payload is part of the cache key if the response is dependent on the payload. For example, if a client makes a POST request with some payload and the resource does not exist, then the 4.04 (Not Found) response can be reused for other requests to the resource until max-age expires. If a client sends malformed application data in the request payload, then the 4.00 (Bad Request) response cannot be reused.

Indeed nothing of this is specified in RFC 7252.

**Comment by fpalombini** [comment]
@ektrah thanks for the clarification, I am still a bit confused though:

> the payload is part of the cache key if the response is dependent on the payload.

Considering that the Proxy cannot know beforehand what the response is going to be, how does the proxy know if it should include or not the payload in the cache key computation?

If the payload of the request is always part of the cache key, then using the cached error 4.04 may not happen even if it should. On the other hand, if it is not, then cached errors may be reused when they shouldn't (unless max-age is used).

In our OSCOAP case, the payload is always different since it includes the COSE object. If the payload is used in the cached key computation, then setting max-age to 0 is only "kind" to the proxy, but is not necessary. Am I missing something?

**Comment by ektrah** [comment]
> how does the proxy know if it should include or not the payload in the cache key computation?

RFC 7252 doesn't specify anything, so the proxy currently cannot know that. So, for now, the payload should always be part of the cache key.

> If the payload is used in the cached key computation, then setting max-age to 0 is only "kind" to the proxy, but is not necessary. 

Note that setting max-age to 0 alone does not prevent a proxy from giving the response to more than one client. Max-age only says that the response cannot be reused when it expires. But if client A makes a request to a proxy and client B makes a request with the same cache key before the proxy has obtained a response from the server, then the proxy can give the response to both clients when it has obtained it.

**Comment by emanjon** [comment]
As payload is clearly part of the cache key, the max-age=0 is never strictly needed. It may be useful in cases where there are legacy proxies, but it clearly increases per-packet overhead. If we keep the option to have an outer max-age=0, then MAY seem appropriate.
