### ISSUE TITLE
RFC 2119 Language Rant

### ISSUE THREAD

**Issue by jimsch** [core-wg/oscoap#52]
Feel free to ignore this completely.  It is mainly  a rant.

How people write 2119 language often time makes me really irritated.  There are number of things that should be done when writing requirements language that people routinely ignore.

1.  If you cannot do something, then state requirements language does not make sense.    Example - in section 4.3.1.2 - how can one possibly encrypt the outer Observe option.  In order to do so it would be required that it not be an outer option.

2.  Items need to be testable.  If you cannot write a test on a statement, then it should not be a statement.  Example - in section 3.2 - the following items SHALL be pre-established.  How does on test this?

3.  Requirements should be on behavior or information transferred between parties.   Other CoAP fields SHALL neither be integrity protected nor encrypted. 

4.  When possible, positive statements need to be used rather than negative ones.  Thus MUST NOT and SHOULD NOT are impossible to test.  You can check that a positive statement is followed, but a negative statement requires that every possible scenario be checked in order to say that a test passes.  Example.
Applications MUST NOT assume that 'sid' values are unique. maps to Applications MUST assume that 'sid' values are non-unique.   The latter can have a test case while the former may or may not be able to have one.

**Comment by emanjon** [comment]
Good comments, we will go through all 2119 language. I do not agree with the idea that all 2119 language needs to be testable and I cannot find any text in RFC2119 stating that. I think statements like "X MUST be uniformly random" is perfectly fine even if it is untestable.

**Comment by jimsch** [comment]
But I think that is a testable statement.  I would agree that most people would not know how to go about doing so, but that is a different problem.

**Comment by cabo** [comment]
The criteria for a MUST is not that it is testable (we don't care about conformance), but that it is a prerequisite for interoperability — some property that this protocol tries to achieve is damaged when the MUST is violated.

So did this walk through 2119-land happen already?

**Comment by jimsch** [comment]
@cabo If I cannot tell if you have or have not done something, I am not sure that I can see how this can ever promote interoperability.   However, as stated at the top of the issue, this is something I think they should consider but is not something they need to do.

I would be interested in an example of a statement that you think needs to be a MUST but which cannot be testeded.

**Comment by jimsch** [comment]
As I said above, a MUST NOT statement is not testable.  Just because you don't do it here does not mean you might not do it later.  (Yes I recognize that the same can be said about a MUST as well.)  I would say that the sentence "The field X can be assumed to contain public information." is an equivalent statement and not requiring the word MUST in it.  It makes a statement about how the field is treated rather than what the content of the field is.

**Comment by cabo** [comment]
We generally try to avoid waiting for implementers to make some inference that would be needed to avoid a security problem.

More generally, you run a protocol to achieve some external effect, and each peer needs to be able to rely on the other (cooperating) peer to exhibit certain behavior.  While the protocol operations themselves are mostly testable, the effects outside of the protocol often are not, but may still need to be governed by RFC 2119 statements.  Similarly with outside effects possibly caused by a non-cooperating peer.
