### ISSUE TITLE
"stop processing the request": 4.01?

### ISSUE THREAD

**Issue by chrysn** [core-wg/oscoap#53]
At several points in request handling, the server can encounter a verification error and must "stop processing the request".

What does that mean in practice?

* No response at all: Causes retransmissions, is not really in line with the request model, and hard to debug.
* RST: Stops retransmissions, but is not better in terms of the request model (after all, on the outer message level, it was a valid request)
* 4.01: Sounds like the right thing to do to me, especially as an unprotected request to the same resource would have elicted the same response, and doing any less would be implicitly admitting that the server *did* try to process the OSCOAP request.

**Comment by gselander** [comment]
Merging #59 with this issue. 

Agree on the need for a a generic security conditions failed response. We should recommend the use of 4.01,  or alternatively a new generic unspecified security error.

Need to go be applied selectively: Don't change the currently defined behavior of silently swallowing known re-plays (based on the sequence number) as there might be issues of responses being re-ordered and a NAK message arriving before a good response.

**Comment by chrysn** [comment]
do we really need to silently swallow anything? in particular: can any legitimate request appear as a replay on OSCOAP layer? i'd think that packages of a sequence number only be sent with one message ID (ie. retransmitted by CON mechanism), and thus are hidden from OSCOAP by message deduplication.

also, #92 is probably related to this.

**Comment by fpalombini** [comment]
I made a proposal for different errors responses in the different case. Trying to avoid retransmission, and not send unnecessary messages, I went with what proposed by Jim in #119 .
