### ISSUE TITLE
Update text on Ciphertext and tag

### ISSUE THREAD

**Issue by emanjon** [core-wg/oscoap#54]
Text in document needs to be updated. For example in the Examples:

Ciph + Tag                       / ciphertext + 8 byte
                                            authentication tag /

But according to COSE, tag is part of the ciphertext.

Likely occurs in other places as well (In this specific example there is no need to talk about tag at all)

**Comment by fpalombini** [comment]
Related to #78 (Examples section). I couldn't see any other place where this appears.
