### ISSUE TITLE
Define and apply a generic security error response

### ISSUE THREAD

**Issue by gselander** [core-wg/oscoap#59]
Given the re-try behavior that has been defined for CoAP, if the OSCOAP message does not decrypt
for any reason, then the same message will be received multiple times (once
for each retry plus the original) each of which will potentially try and
find the security context and decrypt the message.

A GENERIC security
conditions failed response to the first message would prevent the
re-transmissions from occurring and might be the preferred behavior.

Need to go be applied selectively:
Don't change the currently defined behavior of
silently swallowing known re-plays (based on the sequence number) as there
might be issues of responses being re-ordered and a NAK message arriving
before a good response.

**Comment by fpalombini** [comment]
Issue discussing this: #53 , let's move the discussion there.
