### ISSUE TITLE
Section 3.2.1 double defines out_len / output_length

### ISSUE THREAD

**Issue by LudwigSeitz** [core-wg/oscoap#61]
In section 3.2.1.  out_len is defined as "the key/IV size of the AEAD algorithm" and
output_length as "is the size of the AEAD key/IV in bytes encoded as
      an 8-bit unsigned integer"

Isn't that essentially the same?

**Comment by emanjon** [comment]
I just created a v-02 branch for the next update. I'll make an update as soon as possible trying to address this.

**Comment by emanjon** [comment]
Fixed in brach v-02
