### ISSUE TITLE
Optimization of per-packet overhead

### ISSUE THREAD

**Issue by malishav** [core-wg/oscoap#62]
OSCOAP uses COSE as an object security format. COSE is however constructed to support a large number of different stateless use cases, and is not fully optimized for use in a statefull security protocol, leading to a larger than necessary message expansion. In 6TiSCH working group, we would like to avoid fragmentation at all costs which is not easy with 80-90 bytes of available payload with IEEE 802.15.4 radios. Thus, it would be great if OSCOAP could define a compression mechanism to remove the redundant bytes from the COSE/CBOR encoding in the specific use-case of OSCOAP.

**Comment by emanjon** [comment]
I'll look into this. We do have some other preliminary ideas for reducing per-packet overhead when OSCOAP is used with EDHOC, and when OSCOAP is used without Observe.

**Comment by chrysn** [comment]
@malishav, could you give rough ideas on where things start to fragment? reading through draft-ietf-6tisch-minimal-security-01 appendix A, i arrive at a request size of about 60 bytes from JN to JA, and about 64 bytes in the response.

are those the ones that are problematic (or can become problematic under realistic conditions), or is it the edhoc parts, which already exceed the 80-90 bytes in their payloads in some of the examples (esp. message 2) in draft-selander-ace-cose-ecdhe-04?

**Comment by cabo** [comment]
On 22 Feb 2017, at 11:54, Mališa Vučinić <notifications@github.com> wrote:
> 
> redundant bytes

Hi Mališa,

can you quantify that?

Grüße, Carsten

**Comment by malishav** [comment]
Hello Carsten,

Here is a quick example to quantify my issue. OSCOAP uses COSE_Encrypt0 struct of COSE. What will be present in each request is 1) array,  2) one protected headers map, 3) one unprotected headers map and 4) ciphertext. The unprotected headers map will typically be empty in OSCOAP case. Within the protected headers map, OSCOAP transports 'kid' parameter and 'Partial IV' parameter, each encoded with an associated label. 

If we were to transport a single array with the value of kid, Partial IV and ciphertext directly, we would be saving around 4-5 bytes with each OSCOAP message. 

Would that make sense?

**Comment by malishav** [comment]
@chrysn, yes, we would like to avoid fragmentation in the PSK case which is what the example in Appendix A refers to. Note, however, that we are in the process of updating minimal-security draft and the message sizes given in the example change with latest updates. Namely, one will have to add 1) additional authentication tag and freshness indicator for the proxy to verify state information, 2) lease time with the short address and 3) other 802.15.4-specific key information, so the example sizes will increase even in the PSK case.

**Comment by emanjon** [comment]
I have thought about this issue quite a lot during the week. My view is that is both easy and possible to shave these 4-5 bytes. I will add a new appendix later today or tomorrow reducing the per-packet overhead further.

The last weeks we have made at least four other significant chances that has reduced the per-packet overhead:
 - Different "context" identifiers for client and sender
- No sequence number overhead in non-observe responses.
- No encrypted Observe
- Max-Age zero is now MAY.

**Comment by chrysn** [comment]
How will different context identifiers for client and sender benefit 6TiSCH? As I read the current draft, the proxies even rely on them being the same (and to be roundtripped by the server, and oversize) for statelessness.

**Comment by malishav** [comment]
In the latest version of 6tisch-minimal-security draft, we have moved the statelessness mechanism to a new CoAP option so the information is no longer needed to be present as part of the context identifier.

**Comment by gselander** [comment]
The following optimizations have been included in the latest updates: 

    COSE compression
    Different "context" identifiers for client and sender
    No sequence number overhead in non-observe responses.
    No encrypted Observe
    Max-Age zero is now MAY.
