### ISSUE TITLE
Option encoding need to be strictly defined.

### ISSUE THREAD

**Issue by emanjon** [core-wg/oscoap#76]
- The encoding of the encrypted options need to point to RFC7252
- Needs to be defined that the unprotected options are reencoded with new deltas.

**Comment by chrysn** [comment]
ad "reencode with new deltas": IMO the wording "The CoAP options which are of class E (Section 5) are removed. The Object-Security option is added." is sufficient. It operates on the level of a list of options present in a message and not on their byte encoding, and how to encode the resulting smaller list of U options is already specified in CoAP.

**Comment by cabo** [comment]
On 7 Mar 2017, at 08:58, chrysn <notifications@github.com> wrote:
> 
> It operates on the level of a list of options present in a message and not on their byte encoding, and how to encode the resulting smaller list of U options is already specified in CoAP.

Right, but it doesn’t hurt to point out exactly that.

Grüße, Carsten
