### ISSUE TITLE
Protected resources, difference between methods?

### ISSUE THREAD

**Issue by emanjon** [core-wg/oscoap#90]
I think the protected resource section need to include discussion on methods. If I understands correctly, the method is not part of the "resource" definition. A security context may give GET rights but not DELETE rights etc.

**Comment by gselander** [comment]
Not relevant, authorization should be done on CoAP level.

**Comment by cabo** [comment]
Indeed.  See [AIF](https://tools.ietf.org/html/draft-bormann-core-ace-aif-03) for one of the many ways to do this.
