### ISSUE TITLE
Web linking needs IANA registration

### ISSUE THREAD

**Issue by emanjon** [core-wg/oscoap#97]
Also 'sec' seems a bit general, isn't 'oscoap' better.

**Comment by fpalombini** [comment]
yes, lets change it to 'oscoap'

**Comment by gselander** [comment]
1. There is no IANA registration to 'obs' in RFC7641:
https://tools.ietf.org/html/rfc7641#section-6

2. How about 'osc' instead of 'oscoap'?

**Comment by fpalombini** [comment]
@ektrah @cabo could you tell us what you think here? At first sight it seems to me this should be registered with IANA, is that not the case? (couldn't find any registry that list the existing attributes, such as rt, if, sz etc)

**Comment by ektrah** [comment]
There is no registry for link attributes. Link attributes are defined by the link serialization format. If you want to use a new link attribute with RFC 6690, your draft needs to update that RFC. At least this is how I understand RFC 5988bis.

**Comment by fpalombini** [comment]
Ok, thanks, then we don't need to register.
