### ISSUE TITLE
"without leading zeroes"

### ISSUE THREAD

**Issue by chrysn** [core-wg/oscoap#98]
in -02 3.2.1, L is said to be "without leading zeroes". That's a tad confusing IMO given that both its uses are as a number. If this should mean that L is encoded in info's serialization minimally, I suggest that COSE's "CBOR Encoder Restrictions" (effectively prescribing canonical serialization) are used a la

    info is the Canonical CBOR serialization of an array consisting of:

. (By the way, good that it's specified to be the length in bytes now; I and (probably @jimsch) assumed it to be length in bits.)

**Comment by fpalombini** [comment]
You are right, this is confusing. We'll remove the "without leading zeroes" which doesn't make sense here since L is int type.
