### ISSUE TITLE
Type of the replay window

### ISSUE THREAD

**Issue by chrysn** [core-wg/oscoap#99]
The -02 draft introduces the type of the replay window (while it only had a size in -01). Are those types defined somewhere? Is this about "OSCOAP over ordered transports can demand sequentiality" (ie. window size 0 *and* no jumps allowed), can there be others?

(Background: For the request-tag proposal, I'd consider utilizing the window size that is present in the security context as opposed to DTLS where the receiver "does not notify the sender of the window size", and if that can be anything but a sized window, I'd have to adapt.)

**Comment by gselander** [comment]
The replay mechanism may depend on underlying layer (e.g. window size 0 and no jumps allowed for TCP) and application. We don't want to specify this, as there may be different algorithms. And ideally, the request-tag procession should not depend on that either. Alternatively, specify a replay mechanism for which certain processing is valid. Would that work?

**Comment by chrysn** [comment]
The Request-Tag option can be phrased like "if the used sequence number mechanism ensures that none of the aforementioned earlier messages are considered valid by the server after the new message has been unprotected", so a generic but agreed-on mechanism works.

I'd add a line to where the generic replay mechanism is defined that whoever thinks up a replay mechanism should design it in a way that the sender can be sure when the sender will consider old packages (just added that to Request-Tag right now).

I think that with the added note, it'd be clear enough what other mechanisms can be, so from my PoV this can be closed when the Request-Tag texts are imported.

**Comment by chrysn** [comment]
I think that even if it's not specified, there should be some words that hint at what can go on there.

That'd allow repeat-request-tag to say something like "Implementation is trivial in security contexts that have a plain-counter window (cf. [REF]) because they never need a Request-Tag option unless they do concurrent operations."

**Comment by gselander** [comment]
Closed in 7ebec68
